/**
 * MCP Bridge — types + lifecycle interface skeleton
 *
 * This file does **not** implement:
 * - the PoP credential resolver (wholly DEFERRED to a later version)
 * - cross-hop sub-token mint+sign (fail-closed CROSS_HOP_DEFERRED_PHASE6; deferred to a later version)
 * - the idempotency canonical request hash (DEFERRED to a later version)
 * - companion specs references (the relevant spec is not yet published, DEFERRED)
 *
 * This file **implements**:
 * - MCPMessage (the MCP protocol wire payload type)
 * - MCPCallerSubject (PoP-based subject — agentDid / mcpClientId; excludes the 'tokenId' kind)
 * - MCPBridgeError (the error registry)
 * - MCPServerConfig / MCPServerLifecycle (the lifecycle interface)
 *
 * Why it lives in the L4 communication layer (packages/communication):
 * the MCP Bridge is an L4 transport-binding adapter (MCP wire ↔ AP envelope);
 * it sits in the same layer as the HTTP / WebSocket transports; it does not introduce L5 orchestration (orchestration is left for the SDK package to consume as needed).
 */

import type { DID, NegotiationEnvelope } from '@coivitas/types';

// ─── MCP wire payload types ─────────────────────────────────────────────────

// Aligned with @modelcontextprotocol/sdk's JSON-RPC protocol;
// this file only declares the shapes and does not introduce the SDK dependency (the SDK dependency is introduced in the server adapter).

/**
 * MCPClient identifier (per MCP spec — generated by the client itself + persisted to the binding registry at registration)
 *
 * Explicitly bound to the AP `senderDid` via `HolderBindingRegistry`;
 * this type is only a wire-level identifier (binding lookup is implemented by holder-binding-resolver).
 */
export type MCPClientId = string;

/**
 * MCPServer identifier (used for the cross-hop fail-closed decision)
 *
 * Decision logic: `if (nextHopMcpServer !== thisServerId()) return { error: 'CROSS_HOP_DEFERRED_PHASE6' }`
 * This file only introduces the type and does not implement the cross-hop path (fail-closed is implemented by cross-hop-guard).
 */
export type MCPServerId = string;

/**
 * MCP protocol message wire payload (JSON-RPC style)
 *
 * Fields correspond to the MCP spec `tools/call` request:
 * - method: tool name (e.g. `tools/call`)
 * - params: call parameters; the `arguments` substructure holds scope dimensions such as numeric_limit / value / currency
 * - id: JSON-RPC request id
 *
 *  numeric_limit dimension alignment — `params.arguments` substructure fields:
 * - numeric_limit: per-call count cap
 * - value: amount (per-call $)
 * - currency: ISO-4217 string (USD/EUR/...)
 * - timeout / max_iterations: MCP-only; does not affect AP scope (table)
 */
export interface MCPMessage {
    /** JSON-RPC version; MCP defaults to '2.0' */
    jsonrpc: '2.0';
    /** request id (generated by the client; echoed back by the server) */
    id: string | number;
    /** MCP method name (e.g. 'tools/call' / 'tools/list') */
    method: string;
    /** request parameters (the concrete shape varies by method) */
    params?: MCPCallParams;
}

/**
 * The params substructure of MCP `tools/call` (fields corresponding to the ScopeValidator)
 *
 * Fields read by the validation logic:
 * - tool: tool name (for audit / logging)
 * - arguments: call-parameters map
 * - arguments.numeric_limit: aligned with AP `max_per_call`
 * - arguments.value: aligned with AP `max_value_per_call` / `max_total_value`
 * - arguments.currency: AP claim.currency match (top-level guard)
 */
export interface MCPCallParams {
    /** tool name (required by MCP `tools/call`) */
    tool: string;
    /** call-parameters map; the scope-validation fields are in this structure */
    arguments: MCPCallArguments;
}

export interface MCPCallArguments {
    /** per-call count cap */
    numeric_limit?: number;
    /** amount value (validated against max_value_per_call / max_total_value) */
    value?: number;
    /** currency code ISO-4217 (top-level guard; required when max_value_per_call or max_total_value exists) */
    currency?: string;
    /** MCP-only field; does not participate in AP scope validation (recorded for audit but not validated) */
    timeout?: number;
    /** MCP-only field; same as timeout */
    max_iterations?: number;
    /** other tool-specific parameters (passed through, not part of scope validation) */
    [key: string]: unknown;
}

// ─── caller subject (ownership / outbox PoP-based subject) ────────────

// Only PoP-based subjects (agentDid / mcpClientId) are accepted;
// the 'tokenId' kind has been **removed** (tokenId is visible in the envelope/audit = an IDOR-style disclosure risk).

// This type does **not** include a 'tokenId' branch (fail-closed: no partial-acceptance of an auth primitive).

export type MCPCallerSubjectKind = 'agentDid' | 'mcpClientId';

export interface MCPCallerSubject {
    kind: MCPCallerSubjectKind;
    value: string;
}

// ─── error code registry───────────────────────────────────────

// MCP error code strings = user-visible wire values;
// the internal AP code (used for audit / log) keeps its semantics but is not exposed to the MCP client.

export const MCP_ERROR = {
    // holder binding
    BINDING_MISSING: 'mcp_error_binding_missing',
    BINDING_INVALID_SIG: 'mcp_error_binding_invalid_sig',
    BINDING_CONFLICT: 'mcp_error_binding_conflict',
    BINDING_REVOKED: 'mcp_error_binding_revoked',
    BINDING_REVOCATION_UNREACHABLE: 'mcp_error_binding_revocation_unreachable',
    PRINCIPAL_SIG_INVALID: 'mcp_error_principal_sig_invalid',
    POP_INVALID: 'mcp_error_pop_invalid',
    AGENT_DID_UNRESOLVED: 'mcp_error_agent_did_unresolved',

    // capability chain
    CAPABILITY_CHAIN_INVALID: 'mcp_error_capability_chain_invalid',
    CAPABILITY_CHAIN_TOO_DEEP: 'mcp_error_capability_chain_too_deep',

    // cross-hop fail-closed
    CROSS_HOP_DEFERRED: 'mcp_error_cross_hop_deferred',

    // numeric_limit dimension alignment
    SCOPE_INFLATION: 'mcp_error_scope_inflation',
    QUOTA_EXHAUSTED: 'mcp_error_quota_exhausted',
    CURRENCY_MISMATCH: 'mcp_error_currency_mismatch',
    CURRENCY_MISSING: 'mcp_error_currency_missing',
    NO_PER_CALL_SCOPE: 'mcp_error_no_per_call_scope',

    // outbox
    OUTBOX_NOT_FOUND: 'mcp_error_outbox_not_found',
    OUTBOX_UNAUTHORIZED: 'mcp_error_outbox_unauthorized',

    // settlement
    SETTLEMENT_FAILED: 'mcp_error_settlement_failed',

    // token_id format guard
    // a non-UUID-format token_id at the protocol layer → reject; the SQL DDL token_id UUID strong typing forms the second defense layer
    TOKEN_ID_INVALID_FORMAT: 'mcp_error_token_id_invalid_format',
} as const;

export type MCPErrorCode = (typeof MCP_ERROR)[keyof typeof MCP_ERROR];

/**
 * MCP Bridge standard error;
 * client-visible fields = `mcp_code` + `message`; `internalCode` is used for audit / log only.
 */
export interface MCPBridgeError {
    /** MCP wire code (user-visible) */
    mcp_code: MCPErrorCode;
    /** internal code (audit / log only; not returned to the MCP client) */
    internal_code: string;
    /** human-readable message; a non-normative wire field */
    message: string;
}

export function makeMcpError(
    mcp_code: MCPErrorCode,
    internal_code: string,
    message: string,
): MCPBridgeError {
    return { mcp_code, internal_code, message };
}

// ─── L4 envelope conversion interface ──────────────────────────

/**
 * MCP → AP envelope conversion interface
 *
 * Handles a single-hop call:
 * - receives the incoming MCP message + envelope
 * - the same-hop path forwards incomingEnvelope
 * - the cross-hop path is fail-closed with CROSS_HOP_DEFERRED_PHASE6
 *
 * See envelope-adapter.ts for the implementation.
 */
export interface MCPEnvelopeAdapter {
    /**
     * MCP message → AP envelope conversion.
     */
    adaptIncoming(
        mcpMessage: MCPMessage,
        incomingEnvelope: NegotiationEnvelope,
    ): Promise<
        | { ok: true; envelope: NegotiationEnvelope }
        | { ok: false; error: MCPBridgeError }
    >;
}

// ─── MCP server lifecycle interface (wired in server-adapter.ts) ─

/**
 * MCP server transport mode (corresponds to the MCP spec wire transport)
 *
 * - 'http': HTTP POST / WebSocket (used for outbox + streaming flows)
 * - 'stdio': stdin/stdout (@modelcontextprotocol/sdk default; used for local agent invocation)
 *
 * After introducing @modelcontextprotocol/sdk, the TransportFactory is responsible for constructing the corresponding transport instance.
 */
export type MCPServerTransportMode = 'http' | 'stdio';

export interface MCPServerConfig {
    /** server identifier (the thisServerId() return value; used for the cross-hop fail-closed decision) */
    serverId: MCPServerId;
    /** server agent DID (the agent's own AP DID; collaborates with the holder binding but is not directly related) */
    serverDid: DID;
    /** transport mode */
    transport: MCPServerTransportMode;
    /** http transport config (used only when transport='http') */
    http?: {
        /** listen address; '127.0.0.1' / '0.0.0.0' / etc. */
        host?: string;
        /** listen port; 0 = OS auto-allocation (recommended for tests) */
        port: number;
    };
    /** server name (a recognizable name exposed to the MCP client; an MCP capabilities field) */
    serverName?: string;
    /** server version; an MCP capabilities field */
    serverVersion?: string;
}

/**
 * server lifecycle state machine
 *
 * created → starting → running → stopping → stopped
 *                              ↘
 *                                error
 *
 * The lifecycle is the infrastructure required for the server implementation.
 */
export type MCPServerLifecycleState =
    | 'created'
    | 'starting'
    | 'running'
    | 'stopping'
    | 'stopped'
    | 'error';

/**
 * MCP server lifecycle interface
 *
 * `start` / `stop` / `state` / `serverId` are the minimal set;
 * introducing the outbox + scope validator will not change this interface (separate adapters).
 */
export interface MCPServerLifecycle {
    /** current state-machine state (read synchronously) */
    readonly state: MCPServerLifecycleState;
    /** config (read-only after construction) */
    readonly config: MCPServerConfig;
    /** start the server; state created → running or error; idempotent (noop while running) */
    start(): Promise<void>;
    /** stop the server; state running → stopped; idempotent (noop when stopped/created) */
    stop(): Promise<void>;
}

/**
 * MCP server tool handler — used to register tools after introducing @modelcontextprotocol/sdk
 *
 * Pairs with the MCP spec `tools/list` + `tools/call`;
 * this file only provides the type; it is implemented in server-adapter.ts after wiring in the SDK.
 */
export type MCPToolHandler = (
    params: MCPCallParams,
) => Promise<
    { ok: true; result: unknown } | { ok: false; error: MCPBridgeError }
>;

export interface MCPToolDescriptor {
    /** tool name (exposed by MCP `tools/list`) */
    name: string;
    /** tool description (exposed by MCP `tools/list`) */
    description?: string;
    /** parameters JSON Schema (exposed by MCP `tools/list`) */
    inputSchema?: Record<string, unknown>;
    /** call handler */
    handler: MCPToolHandler;
}
