-- 024_sso_federation.sql -- SSO tenant federation mapping table + identity link table

-- tenant federation persistence layer (federation_mapping + federation_identity_links).
-- Pre-allocated sequence number 024 (SQL sequence allocation table
-- 021=multi-tenant / 022=console / 024=sso federation; 023=revocation_records).

-- Design principles (fail-closed + strong multi-tenant isolation A42):
-- - federation_mapping: IDP registry, each row binds one IDP entity (idp_identifier UNIQUE)
-- allowed_tenant_ids restricts the set of tenants the IDP may assert; the basis of CROSS_TENANT_ASSERTION defense.
-- - federation_identity_links: external identity (IDP external_subject) ← → users mapping
-- one user maps to one IDP external identity (UNIQUE external_subject + idp_identifier).
-- - the tenants table is created by 008-create-managed-service-tenants.sql (not recreated in this file).
-- - the users + events tables are created by 025_managed_service_users_events.sql.
-- - all primary keys are UUID: gen_random_uuid() (pgcrypto extension).

-- Security constraints:
-- - idp_signing_cert / idp_jwks_uri: trust-chain entry points, must be written via the admin interface; the application layer
-- must never write user-controlled data directly into these two columns (SQL CHECK constraints cannot fully cover this; relies on the application-layer guard).
-- - allowed_tenant_ids: TEXT[] NOT NULL DEFAULT '{}' (empty array = IDP has no right to assert any tenant).
-- - idp_type CHECK constraint: strictly limited to 'saml' | 'oidc', no arbitrary strings.

-- pgcrypto: gen_random_uuid() dependency.
-- IF NOT EXISTS ensures idempotency (same declaration as migration 008).
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- managed_service schema: unified home for JIT provisioning / SSO federation / tenants.
-- IF NOT EXISTS ensures idempotency (consistent with 008-create-managed-service-tenants.sql L31).
CREATE SCHEMA IF NOT EXISTS managed_service;

-- =====================================================================
-- Table 1: federation_mapping (IDP registry)
-- =====================================================================
-- Each row represents a registered IDP entity (SAML EntityID or OIDC issuer).
-- The application layer looks this table up by idp_identifier (findIdpMapping call site)
-- No matching idp_identifier → FED_IDP_NOT_REGISTERED (fail-closed).

-- Critical security fields:
-- idp_signing_cert — SAML assertion signature verification public key (PEM; null = OIDC IDP)
-- idp_jwks_uri — OIDC JWKS endpoint (null = SAML IDP)
-- allowed_tenant_ids — the set of tenant_id values this IDP may assert (empty array = no right to assert any tenant)

-- idp_signing_cert and idp_jwks_uri are the trust-chain entry point for an entire tenant:
-- tampering with either field → an attacker can forge that IDP's assertions → the entire tenant's identity is compromised (P0 security incident).
-- These two columns must never be written directly by clients; they must be operated on via an admin-privileged API.
CREATE TABLE IF NOT EXISTS managed_service.federation_mapping (
    -- Primary key UUID (not generated by the application layer; DB does it automatically)
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- IDP unique identifier
    -- SAML: EntityID (https://example.com/saml/idp)
    -- OIDC: issuer URL (https://accounts.google.com)
    -- UNIQUE: the same IDP can only be registered once; duplicate registration → DB UNIQUE VIOLATION → 409
    idp_identifier      TEXT NOT NULL UNIQUE,

    -- IDP type (strict enum; fail-closed)
    idp_type            TEXT NOT NULL,

    -- The set of tenant_id values this IDP is allowed to assert
    -- [] = empty set → every assertion is rejected (FED_CROSS_TENANT_ASSERTION)
    -- ['tenant-a', 'tenant-b'] = only these two tenants are allowed
    -- DEFAULT empty array: a newly registered IDP has no right to assert any tenant by default (fail-closed)
    allowed_tenant_ids  TEXT[]  NOT NULL DEFAULT '{}',

    -- SAML assertion signature verification public key (PEM format; not required for OIDC IDPs)
    -- NULL = not configured (OIDC IDP) or pending configuration (requires explicit admin write)
    -- Security warning: this field is the SAML trust-chain entry point; only admin privileges may write it
    idp_signing_cert    TEXT,

    -- OIDC JWKS endpoint URL (not required for SAML IDPs)
    -- NULL = not configured (SAML IDP)
    -- Security warning: this field is the OIDC trust-chain entry point; only admin privileges may write it
    idp_jwks_uri        TEXT,

    -- Record creation time (DB server-side time)
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Last update time (updated when an admin changes allowed_tenant_ids / cert / jwks)
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- idp_type strict enum constraint (fail-closed: illegal values are rejected by the DB directly)
    CONSTRAINT ck_federation_mapping_idp_type CHECK (idp_type IN ('saml', 'oidc')),

    -- idp_identifier length limit (anti-DoS; matches the application-layer 256-character truncation)
    CONSTRAINT ck_federation_mapping_idp_identifier_length CHECK (char_length(idp_identifier) <= 512)
);

-- idp_identifier is already UNIQUE (the UNIQUE constraint above implicitly builds an index)
-- Add a filtering index on idp_type (admin console groups queries by type)
CREATE INDEX IF NOT EXISTS ix_federation_mapping_idp_type
    ON managed_service.federation_mapping (idp_type);

-- Descending index on updated_at DESC (admin console list sorting)
CREATE INDEX IF NOT EXISTS ix_federation_mapping_updated_at
    ON managed_service.federation_mapping (updated_at DESC);

COMMENT ON TABLE managed_service.federation_mapping IS
    'SSO IDP registry (SAML + OIDC).'
    'allowed_tenant_ids empty array = IDP has no right to assert any tenant (fail-closed P1.1).'
    'idp_signing_cert / idp_jwks_uri are trust-chain entry points: only admin privileges may write them.'
    'Pre-allocated sequence number 024.';

COMMENT ON COLUMN managed_service.federation_mapping.idp_signing_cert IS
    'SAML assertion signature verification public key (PEM).'
    'Security warning: this field is the SAML trust-chain entry point; tampering → an attacker can forge assertions → the entire tenant identity is compromised.'
    'Must never be written directly by clients; must go through an admin-privileged API.';

COMMENT ON COLUMN managed_service.federation_mapping.idp_jwks_uri IS
    'OIDC JWKS endpoint URL.'
    'Security warning: this field is the OIDC trust-chain entry point; tampering → an attacker can forge JWTs → the entire tenant identity is compromised.'
    'Must never be written directly by clients; must go through an admin-privileged API.';

COMMENT ON COLUMN managed_service.federation_mapping.allowed_tenant_ids IS
    'The set of tenant_id values the IDP is allowed to assert (TEXT[]).'
    'Empty array = fail-closed: the IDP has no right to assert any tenant.'
    'Basis of CROSS_TENANT_ASSERTION defense: the application layer verifies assertedTenantId ∈ allowed_tenant_ids.';

-- =====================================================================
-- Table 2: federation_identity_links (external identity ↔ internal user mapping)
-- =====================================================================
-- Each row represents a persistent "external IDP identity → internal user" binding.
-- JIT user provisioning (createUser call site) writes to this table within a transaction.

-- UNIQUE (idp_identifier, external_subject):
-- prevents the same external identity from being bound to two internal users (basis of IDENTITY_REBIND_REJECTED defense).

-- findUserByExternalSubject call path:
-- JOIN users u ON u.id = fil.user_id WHERE fil.external_subject = $1 AND fil.idp_identifier = $2
CREATE TABLE IF NOT EXISTS managed_service.federation_identity_links (
    -- Primary key UUID
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Internal user ID (FK → users.id; CASCADE: the link is deleted when the user is deleted)
    -- Note: the users table is created by an earlier migration (008, etc.)
    user_id             UUID NOT NULL,

    -- Identifier of the IDP the external identity belongs to (corresponds to federation_mapping.idp_identifier)
    idp_identifier      TEXT NOT NULL,

    -- External identity subject identifier (SAML NameID or OIDC sub claim)
    -- Jointly unique with idp_identifier (prevents the same external identity from being bound to multiple internal users)
    external_subject    TEXT NOT NULL,

    -- Link creation time (written at JIT provisioning time)
    linked_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Joint uniqueness constraint: the same (idp_identifier, external_subject) can bind only one user
    -- UNIQUE VIOLATION → caught by the application layer → FED_IDENTITY_REBIND_REJECTED (fail-closed)
    CONSTRAINT uniq_federation_identity_links_idp_subject
        UNIQUE (idp_identifier, external_subject),

    -- external_subject length limit (anti-DoS)
    CONSTRAINT ck_federation_identity_links_external_subject_length
        CHECK (char_length(external_subject) <= 512),

    -- idp_identifier length limit (same constraint as federation_mapping)
    CONSTRAINT ck_federation_identity_links_idp_identifier_length
        CHECK (char_length(idp_identifier) <= 512)
);

-- High-frequency query path: look up by (external_subject, idp_identifier) (findUserByExternalSubject call path)
-- The UNIQUE constraint already implicitly builds an index on (idp_identifier, external_subject)
-- But the application-layer WHERE clause puts external_subject first, so add a reverse index to cover both query directions
CREATE INDEX IF NOT EXISTS ix_federation_identity_links_subject_idp
    ON managed_service.federation_identity_links (external_subject, idp_identifier);

-- Look up by user_id (used for user-delete cascade checks / admin console user identity link list)
CREATE INDEX IF NOT EXISTS ix_federation_identity_links_user_id
    ON managed_service.federation_identity_links (user_id);

-- Look up by idp_identifier (admin console: view all users bound under a given IDP)
CREATE INDEX IF NOT EXISTS ix_federation_identity_links_idp_identifier
    ON managed_service.federation_identity_links (idp_identifier);

COMMENT ON TABLE managed_service.federation_identity_links IS
    'External IDP identity ↔ internal user mapping table (written by JIT provisioning).'
    'UNIQUE (idp_identifier, external_subject) prevents the same external identity from binding multiple users.'
    'UNIQUE VIOLATION → FED_IDENTITY_REBIND_REJECTED (fail-closed P1.1).'
    'Pre-allocated sequence number 024.';

COMMENT ON COLUMN managed_service.federation_identity_links.external_subject IS
    'SAML NameID or OIDC sub claim (unique identifier of the external identity).'
    'Jointly unique with idp_identifier: prevents the same external identity from binding multiple internal users.'
    'The DB-layer anchor for IDENTITY_REBIND_REJECTED defense.';

-- =====================================================================
-- schema_migrations version record
-- =====================================================================
-- Same pattern as other migrations: INSERT OR IGNORE (idempotent).
-- If the schema_migrations table does not exist (fresh DB) it is managed by the external migration runner
-- Here a DO $$ ... $$ block performs a defensive insert to avoid an error when schema_migrations is absent.
DO $$
BEGIN
    -- Only insert the version record if the schema_migrations table exists
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'schema_migrations'
    ) THEN
        INSERT INTO schema_migrations (version, applied_at)
        VALUES ('024', NOW())
        ON CONFLICT (version) DO NOTHING;
    END IF;
END;
$$;
