/**
 * ap session encrypt — debug-only AEAD encryption CLI command
 *
 * Purpose: invoke envelope AEAD encryption directly in demo/debug scenarios, with no running session.
 * It inline-builds a lightweight mock SessionRegistry + SessionCryptoHandle,
 * calls encryptEnvelopeBody, and outputs { ciphertext, aad, encryptedPayload }.
 *
 * Note: this command is for development debugging only; production encryption is managed by HandshakeInitiator/Responder + SessionManager.
 *
 */

import { randomUUID, randomBytes } from 'node:crypto';

import { Command } from 'commander';

import {
    encryptEnvelopeBody,
    SessionRegistryImpl,
} from '@coivitas/communication';
import type { AeadAadFields } from '@coivitas/types';

import { printOutput } from '../runtime.js';

// ── Command body ──────────────────────────────────────────────────────────────────

export interface SessionEncryptOptions {
    sessionId: string;
    plaintext: string;
    tokenId: string;
}

/**
 * Execution body (extracted for unit testing)
 *
 * Implementation details:
 * 1. Randomly generate 32B traffic keys (initToResp / respToInit) + 4B sessionSalt + 32B rekeyChainKey
 * 2. Register the session via SessionRegistryImpl.createSession
 * 3. Call encryptEnvelopeBody (bodyType: 'BUSINESS')
 * 4. Return { ciphertext, aad, encryptedPayload }
 *
 * Security boundary: keys generated by randomBytes differ on every call and are for demo/debug only;
 * in production use the full handshake protocol (HandshakeInitiator/Responder).
 */
export function runSessionEncrypt(options: SessionEncryptOptions): Promise<{
    ciphertext: string;
    aad: Record<string, unknown>;
    encryptedPayload: Record<string, unknown>;
}> {
    const { sessionId, plaintext, tokenId } = options;

    // Build debug key material (random, not persisted)
    const initToResp = new Uint8Array(randomBytes(32));
    const respToInit = new Uint8Array(randomBytes(32));
    const sessionSalt = new Uint8Array(randomBytes(4));
    const rekeyChainKey = new Uint8Array(randomBytes(32));

    // Register the session
    const registry = new SessionRegistryImpl();
    registry.createSession(sessionId, 'initiator', tokenId, {
        trafficKeys: { initToResp, respToInit },
        sessionSalt,
        rekeyChainKey,
        generation: 0,
    });

    const envelopeId = randomUUID();
    const messageType = 'DEBUG_ENCRYPT';

    const aadFields: AeadAadFields = {
        envelopeId,
        messageType,
    };

    const plaintextBytes = new TextEncoder().encode(plaintext);

    const encryptedBody = encryptEnvelopeBody({
        registry,
        sessionId,
        capabilityTokenRef: tokenId,
        aadFields,
        plaintext: plaintextBytes,
        bodyType: 'BUSINESS',
    });

    const result = {
        ciphertext: encryptedBody.ciphertext,
        aad: {
            envelopeId,
            messageType,
            keyId: encryptedBody.keyId,
            aeadNonce: encryptedBody.aeadNonce,
        },
        encryptedPayload: {
            encrypted: encryptedBody.encrypted,
            encryptionProtocolVersion: encryptedBody.encryptionProtocolVersion,
            type: encryptedBody.type,
            ciphertext: encryptedBody.ciphertext,
            aeadNonce: encryptedBody.aeadNonce,
            keyId: encryptedBody.keyId,
        },
    };

    // Cleanup: close the debug session (CLOSED = normal termination)
    registry.closeSession(sessionId, 'CLOSED');

    return Promise.resolve(result);
}

export const createSessionEncryptCommand = (): Command => {
    const command = new Command('session').description(
        'Session-layer utilities.',
    );

    command
        .command('encrypt')
        .description(
            'Debug: AEAD-encrypt a plaintext string using a stub session handle (demo/debug only, not for production).',
        )
        .requiredOption(
            '--session-id <SID>',
            'Session ID to use for the stub registry.',
        )
        .requiredOption('--plaintext <text>', 'Plaintext string to encrypt.')
        .requiredOption(
            '--token-id <TID>',
            'Capability token ID for the authorizedTokenId binding.',
        )
        .action(async (options: SessionEncryptOptions) => {
            const result = await runSessionEncrypt(options);
            printOutput(result, true);
        });

    return command;
};
