"""RFC 8785 JCS canonicalization conformance.

TS same-source
--------------
- TS implementation: ``packages/crypto/src/canonicalization.ts`` (wraps the npm ``canonicalize``)
- Prerequisite for cross-language byte-level wire format consistency

Cross-language alignment contract
---------------------------------
This test does **not** depend on whether a specific TS test file exists; it directly asserts that the
Python ``canonicalize`` output is byte-level correct for several **deterministic RFC 8785 test vectors**:

1. Key order: UTF-16 code unit sorting (equivalent to codepoint sorting within the ASCII range)
2. Strings: standard JSON escaping (quotation / backslash / control char)
3. Numbers: integers have no decimal point; floats use the shortest representation (ECMA-262 ToString equivalent)
4. Arrays: preserve input order
5. fail-closed: bytes / set / NaN / Infinity / circular references → WireSerializationError

Anti self-equal
---------------
Every assert reaches the ``coivitas._wire.canonicalize`` production implementation; inputs are
RFC 8785 standard vectors or vectors reconciled against the TS canonicalize output.
"""

from __future__ import annotations

import math

import pytest

from coivitas._wire import (
    WireSerializationError,
    canonicalize,
    envelope_from_wire,
    envelope_to_wire,
)


class TestCanonicalizeBasicShape:
    """RFC 8785 §3.2.3 key order + §3.2.5 array order preservation."""

    def test_object_keys_sorted_ascii(self) -> None:
        """Object keys are sorted by codepoint (byte-consistent with TS canonicalize)."""
        result = canonicalize({"b": 2, "a": 1, "c": 3})
        # RFC 8785: within ASCII, a < b < c
        assert result == '{"a":1,"b":2,"c":3}'

    def test_array_preserves_order(self) -> None:
        """Arrays preserve input order (no sorting)."""
        result = canonicalize([3, 1, 2])
        assert result == "[3,1,2]"

    def test_nested_object_keys_recursively_sorted(self) -> None:
        """Nested object keys are sorted recursively."""
        result = canonicalize({"z": {"y": 1, "x": 2}, "a": [1, 2, 3]})
        assert result == '{"a":[1,2,3],"z":{"x":2,"y":1}}'

    def test_empty_object_and_array(self) -> None:
        """Minimal output for empty object / empty array."""
        assert canonicalize({}) == "{}"
        assert canonicalize([]) == "[]"


class TestCanonicalizeNumericFormatting:
    """RFC 8785 §3.2.2 + ECMA-262 ToString number formatting."""

    def test_integer_no_decimal_point(self) -> None:
        """Integers: no decimal point (consistent with ECMA-262 ToString)."""
        assert canonicalize({"n": 1}) == '{"n":1}'
        assert canonicalize({"n": 0}) == '{"n":0}'
        assert canonicalize({"n": -42}) == '{"n":-42}'

    def test_integer_float_no_decimal_point(self) -> None:
        """1.0 → "1" (consistent with ECMA-262 ToString; integer floats have no decimal point)."""
        assert canonicalize({"n": 1.0}) == '{"n":1}'
        assert canonicalize({"n": 0.0}) == '{"n":0}'

    def test_negative_zero_normalized(self) -> None:
        """Negative zero: both Python and JS emit "0" (ECMA-262 ToString -0 → "0")."""
        # Python int(-0.0) == 0; consistent with TS behavior
        assert canonicalize({"n": -0.0}) == '{"n":0}'

    def test_nan_and_infinity_fail_closed(self) -> None:
        """NaN / Infinity are not serializable → WireSerializationError."""
        with pytest.raises(WireSerializationError, match="Non-finite"):
            canonicalize({"n": float("nan")})
        with pytest.raises(WireSerializationError, match="Non-finite"):
            canonicalize({"n": float("inf")})
        with pytest.raises(WireSerializationError, match="Non-finite"):
            canonicalize({"n": -math.inf})


class TestCanonicalizeEcma262NumberToString:
    """ECMA-262 §7.1.12.1 ToString(Number) boundary vectors.

    fixture source
    --------------
    All expected values are generated by running the TS-side canonicalize npm package via
    ``node -e "console.log(require('canonicalize')({n: <val>}))"`` at the repo root; not self-equal — the
    Python-side ``_format_number`` must independently implement the ECMA-262 algorithm and match byte-for-byte.

    Boundaries covered
    ------------------
    - epsilon region (1e-7 vs 1e-6): branch 3↔4 boundary (``−6 < n ≤ 0`` upper bound)
    - large integer floats (1e20 vs 1e21): branch 1↔4 boundary (``n ≤ 21`` upper bound)
    - mid precision (1e15 / 1e16): still takes branch 1 (fixed point)
    - double-precision extremes (5e-324 / 1.7976931348623157e+308): branch 4 scientific notation
    - round-trip precision (9.999999999999999e-7 → "0.000001"): repr shortest representation
    """

    @pytest.mark.parametrize(
        "value,expected",
        [
            # epsilon: branch boundary
            (1e-6, "0.000001"),
            (1e-7, "1e-7"),
            (3e-7, "3e-7"),
            # round-trip boundary (Grisu shortest round-trippable → consistent with V8)
            (9.999999999999999e-7, "0.000001"),
            # large integer floats: branch 1↔4 boundary
            (1e15, "1000000000000000"),
            (1e16, "10000000000000000"),
            (1e20, "100000000000000000000"),
            (1e21, "1e+21"),
            (1e22, "1e+22"),
            # standard decimal / integer / integer float
            (0.1, "0.1"),
            (1.5, "1.5"),
            (2.5, "2.5"),
            (100, "100"),
            (100.0, "100"),
            (-1.5, "-1.5"),
            # zero / negative zero (ECMA step 2)
            (0, "0"),
            (-0.0, "0"),
            # double-precision extremes
            (5e-324, "5e-324"),
            (1.7976931348623157e308, "1.7976931348623157e+308"),
        ],
    )
    def test_ecma_262_to_string_byte_equal_to_ts(
        self, value, expected
    ) -> None:
        """Python ``canonicalize`` output is byte-level consistent with TS ``canonicalize({n:value})``.

        The fixture is generated by running the TS canonicalize npm package (i.e. the internal
        dependency of packages/crypto/src/canonicalization.ts) via
        ``node -e "console.log(require('canonicalize')({n:<val>}))"``.
        """
        got = canonicalize({"n": value})
        assert got == f'{{"n":{expected}}}', (
            f"Python canonicalize drift from TS at value={value!r}:\n"
            f"  got     ={got!r}\n  expected={{'n':{expected}}}!r"
        )

    def test_nan_rejected_jcs_does_not_allow(self) -> None:
        """RFC 8785 / JCS forbids NaN."""
        with pytest.raises(WireSerializationError, match="Non-finite"):
            canonicalize({"n": float("nan")})

    def test_positive_infinity_rejected(self) -> None:
        """RFC 8785 / JCS forbids +Infinity."""
        with pytest.raises(WireSerializationError, match="Non-finite"):
            canonicalize({"n": float("inf")})

    def test_negative_infinity_rejected(self) -> None:
        """RFC 8785 / JCS forbids -Infinity."""
        with pytest.raises(WireSerializationError, match="Non-finite"):
            canonicalize({"n": -math.inf})


class TestCanonicalizeUtf16CodeUnitSort:
    """RFC 8785 §3.2.3 UTF-16 code unit lexicographic sorting.

    fixture source
    --------------
    All expected values are generated by running the TS canonicalize npm package via
    ``node -e "console.log(require('canonicalize')({...}))"`` at the repo root; not self-equal.

    Boundaries
    ----------
    - BMP characters (U+0000..U+FFFF): codepoint == UTF-16 code unit, equivalent to the default
      Python sorted
    - supplementary characters (U+10000+): UTF-16 surrogate pair (lead unit 0xD8XX..0xDBXX
      < 0xFFXX high BMP); sorting by codepoint is in the opposite direction of sorting by UTF-16
    - Before the fix, Python ``sorted(keys)`` used codepoint, so the relative order of supplementary
      vs high-BMP characters disagreed with TS; after the fix, using ``utf-16-be`` byte order matches TS.
    """

    def test_bmp_ascii_keys_sorted(self) -> None:
        """ASCII range (including 0x41 'A' < 0x61 'a')."""
        # node verification: `{"A":4,"B":5,"a":1,"b":2,"c":3}`
        assert canonicalize(
            {"b": 2, "a": 1, "c": 3, "A": 4, "B": 5}
        ) == '{"A":4,"B":5,"a":1,"b":2,"c":3}'

    def test_supplementary_plane_before_high_bmp(self) -> None:
        """U+10000 (𐀀, UTF-16 [0xD800,0xDC00]) sorts before U+FFFD (�).

        Python codepoint sorting would place U+10000 later (codepoint 0x10000 > 0xFFFD),
        the opposite of the TS-side JS default sort — UTF-16 code unit sorting is required for byte-level consistency.

        node fixture: `{"𐀀":1,"�":2}` (note 𐀀 comes first)
        """
        keys = {chr(0x10000): 1, chr(0xFFFD): 2}
        got = canonicalize(keys)
        assert got == '{"\U00010000":1,"�":2}', got

    def test_supplementary_pair_with_suffix(self) -> None:
        """supplementary + ASCII suffix vs BMP + ASCII suffix; the lead code unit decides the order.

        node fixture: `{"𐀀b":1,"�a":2}`
        """
        keys = {chr(0x10000) + "b": 1, chr(0xFFFD) + "a": 2}
        got = canonicalize(keys)
        assert got == '{"\U00010000b":1,"�a":2}', got

    def test_emoji_with_bmp_ideograph(self) -> None:
        """U+1F600 😀 is [0xD83D, 0xDE00] in UTF-16; the lead unit 0xD83D < 0xFF21
        (Ａ U+FF21 fullwidth A); Python codepoint sorting would reverse the order.

        node fixture: `{"a":2,"😀":1,"Ａ":3}`
        """
        keys = {chr(0x1F600): 1, "a": 2, "Ａ": 3}
        got = canonicalize(keys)
        assert got == '{"a":2,"\U0001F600":1,"Ａ":3}', got

    def test_chinese_bmp_keys_sorted_consistently(self) -> None:
        """Chinese (BMP) key order: 'a'(0x61) < '中'(0x4E2D) < '文'(0x6587).

        Within the BMP, codepoint == UTF-16 code unit, so TS / Python are equivalent; this test guards that
        the fix does not break existing BMP behavior.

        node fixture: `{"a":3,"中":1,"文":2}`
        """
        got = canonicalize({"中": 1, "文": 2, "a": 3})
        assert got == '{"a":3,"中":1,"文":2}'


class TestCanonicalizeStringEscaping:
    """RFC 8785 §3.2.1 string escaping (standard JSON)."""

    def test_simple_ascii_string(self) -> None:
        assert canonicalize({"s": "hello"}) == '{"s":"hello"}'

    def test_quotation_escaped(self) -> None:
        assert canonicalize({"s": 'a"b'}) == '{"s":"a\\"b"}'

    def test_backslash_escaped(self) -> None:
        assert canonicalize({"s": "a\\b"}) == '{"s":"a\\\\b"}'

    def test_control_chars_escaped(self) -> None:
        # \n / \t standard JSON escaping (consistent with TS canonicalize)
        assert canonicalize({"s": "a\nb"}) == '{"s":"a\\nb"}'
        assert canonicalize({"s": "a\tb"}) == '{"s":"a\\tb"}'

    def test_unicode_preserved_no_ascii_escape(self) -> None:
        """Non-ASCII Unicode is not escaped to \\uXXXX (consistent with TS canonicalize)."""
        assert canonicalize({"s": "héllo"}) == '{"s":"héllo"}'
        assert canonicalize({"s": "中文"}) == '{"s":"中文"}'


class TestCanonicalizeFailClosed:
    """fail-closed defense (consistent with TS assertSerializable)."""

    def test_bytes_rejected(self) -> None:
        with pytest.raises(WireSerializationError, match="Unsupported"):
            canonicalize({"b": b"raw"})

    def test_set_rejected(self) -> None:
        with pytest.raises(WireSerializationError, match="Unsupported"):
            canonicalize({"s": {1, 2, 3}})

    def test_function_rejected(self) -> None:
        with pytest.raises(WireSerializationError, match="Unsupported"):
            canonicalize({"f": lambda: None})

    def test_circular_reference_rejected(self) -> None:
        a: dict = {"name": "a"}
        a["self"] = a
        with pytest.raises(WireSerializationError, match="Circular"):
            canonicalize(a)

    def test_non_string_keys_rejected(self) -> None:
        with pytest.raises(WireSerializationError, match="Non-string key"):
            canonicalize({1: "value"})


class TestCanonicalizePrimitives:
    """null / bool / number / string at the top level."""

    def test_null_value(self) -> None:
        assert canonicalize({"n": None}) == '{"n":null}'

    def test_bool_values(self) -> None:
        assert canonicalize({"a": True, "b": False}) == '{"a":true,"b":false}'


class TestEnvelopeWireRoundtrip:
    """envelope wire format roundtrip (byte-level consistency prerequisite)."""

    def test_envelope_to_wire_byte_stable(self) -> None:
        """Serializing equivalent envelope dicts is byte-level stable (independent of key insertion order)."""
        env1 = {
            "id": "env-1",
            "specVersion": "0.1.0",
            "messageType": "NEGOTIATION_REQUEST",
            "header": {
                "senderDid": "did:agent:" + "a" * 40,
                "recipientDid": "did:agent:" + "b" * 40,
                "sessionId": None,
            },
            "body": {"action": "INQUIRY", "params": {}},
            "signature": "0" * 128,
            "timestamp": "2026-05-07T12:00:00.000Z",
        }
        env2 = {
            # intentionally reversed key insertion; canonicalize must emit the same bytes
            "timestamp": "2026-05-07T12:00:00.000Z",
            "signature": "0" * 128,
            "body": {"params": {}, "action": "INQUIRY"},
            "header": {
                "sessionId": None,
                "recipientDid": "did:agent:" + "b" * 40,
                "senderDid": "did:agent:" + "a" * 40,
            },
            "messageType": "NEGOTIATION_REQUEST",
            "specVersion": "0.1.0",
            "id": "env-1",
        }
        wire1 = envelope_to_wire(env1)
        wire2 = envelope_to_wire(env2)
        assert wire1 == wire2, (
            f"canonicalize wire bytes drift across key insertion order:\n"
            f"  wire1={wire1!r}\n  wire2={wire2!r}"
        )

    def test_wire_roundtrip_preserves_data(self) -> None:
        """envelope_from_wire(envelope_to_wire(env)) ≡ env (semantically equivalent)."""
        env = {
            "id": "env-roundtrip",
            "specVersion": "0.1.0",
            "messageType": "ERROR",
            "header": {
                "senderDid": "did:agent:" + "f" * 40,
                "recipientDid": "did:agent:" + "0" * 40,
                "sessionId": "sess-001",
            },
            "body": {"code": "INVALID_ENVELOPE", "message": "test"},
            "signature": "1" * 128,
            "timestamp": "2026-05-07T12:00:00.000Z",
        }
        wire = envelope_to_wire(env)
        decoded = envelope_from_wire(wire)
        assert decoded == env, (
            f"roundtrip lost data:\n  in={env}\n  out={decoded}"
        )

    def test_wire_invalid_payload_fails_closed(self) -> None:
        """wire bytes that are non-JSON / non-object → WireSerializationError."""
        with pytest.raises(WireSerializationError):
            envelope_from_wire(b"not-json")
        with pytest.raises(WireSerializationError):
            envelope_from_wire(b'"a string"')
        with pytest.raises(WireSerializationError):
            envelope_from_wire(b"[1, 2, 3]")


# ─── JS Number safe integer range guard ───────────────────────────────────


class TestJsSafeIntegerR3FixF2:
    """Reject integers beyond ±(2^53-1); guards against byte-level interop drift between
    Python arbitrary-precision int and JS Number IEEE-754 double precision.

    Anchor: ``packages/sdk-python/src/coivitas/_wire.py`` ``_check_js_safe_integer``.
    """

    def test_safe_max_boundary_accepted(self) -> None:
        """Positive boundary: 2^53 - 1 = 9007199254740991 (JS Number.MAX_SAFE_INTEGER) is valid."""
        result = canonicalize({"n": 2**53 - 1})
        assert result == '{"n":9007199254740991}'

    def test_safe_min_boundary_accepted(self) -> None:
        """Positive boundary: -(2^53 - 1) is valid."""
        result = canonicalize({"n": -(2**53 - 1)})
        assert result == '{"n":-9007199254740991}'

    def test_max_plus_one_rejected(self) -> None:
        """2^53 = 9007199254740992 → reject (JS Number has begun losing precision)."""
        with pytest.raises(WireSerializationError, match="JS safe range"):
            canonicalize({"n": 2**53})

    def test_max_plus_two_rejected(self) -> None:
        """2^53 + 1 = 9007199254740993 → reject (the classic precision-loss case: JS Number
        cannot distinguish 9007199254740992 from 9007199254740993)."""
        with pytest.raises(WireSerializationError, match="JS safe range"):
            canonicalize({"n": 2**53 + 1})

    def test_min_minus_one_rejected(self) -> None:
        """-(2^53) → reject (outside the negative boundary)."""
        with pytest.raises(WireSerializationError, match="JS safe range"):
            canonicalize({"n": -(2**53)})

    def test_huge_int_rejected(self) -> None:
        """10^20 → reject (far beyond the JS safe range)."""
        with pytest.raises(WireSerializationError, match="JS safe range"):
            canonicalize({"n": 10**20})

    def test_format_number_direct_invocation_rejected(self) -> None:
        """Double defense: _format_number also rejects when invoked directly (protects future refactor paths)."""
        from coivitas._wire import _format_number

        with pytest.raises(WireSerializationError, match="JS safe range"):
            _format_number(2**53 + 1)


# ─── base64url strict padding (={0,2}) ────────────────────────────────────


class TestBase64UrlStrictPaddingR3FixF3:
    """from_base64url tightens padding validation (trailing ``=`` 0-2);
    1:1 with TS ``packages/crypto/src/encoding.ts``
    ``BASE64URL_PATTERN = /^[A-Za-z0-9_-]*={0,2}$/``.

    Before tightening, Python ``rstrip("=")`` leniently accepted pathological inputs such as
    ``"AA==="`` / ``"AA===="`` while the TS side rejected them → byte-level interop drift.
    """

    def test_no_padding_accepted(self) -> None:
        """No padding is valid (``"AA"`` → 1 byte)."""
        from coivitas._wire import from_base64url

        assert from_base64url("AA") == b"\x00"

    def test_one_padding_accepted(self) -> None:
        """1 padding char is valid (``"AA="``)."""
        from coivitas._wire import from_base64url

        assert from_base64url("AA=") == b"\x00"

    def test_two_padding_accepted(self) -> None:
        """2 padding chars are valid (``"AA=="``)."""
        from coivitas._wire import from_base64url

        assert from_base64url("AA==") == b"\x00"

    def test_three_padding_rejected(self) -> None:
        """3 padding chars are rejected (TS BASE64URL_PATTERN ={0,2} upper bound)."""
        from coivitas._wire import from_base64url

        with pytest.raises(WireSerializationError, match="padding"):
            from_base64url("AA===")

    def test_four_padding_rejected(self) -> None:
        """4 padding chars are rejected."""
        from coivitas._wire import from_base64url

        with pytest.raises(WireSerializationError, match="padding"):
            from_base64url("AA====")

    def test_illegal_charset_rejected(self) -> None:
        """Illegal character (``*`` is not in [A-Za-z0-9_-]) → reject."""
        from coivitas._wire import from_base64url

        with pytest.raises(WireSerializationError):
            from_base64url("AA*")

    def test_brand_validator_directly_callable(self) -> None:
        """Type-layer _check_base64url unit-test grounding (the public surface goes through Annotated[Base64Url])."""
        from coivitas._brands import _check_base64url

        # valid
        assert _check_base64url("AA") == "AA"
        assert _check_base64url("AA==") == "AA=="
        assert _check_base64url("") == ""  # empty string is valid (consistent with the TS pattern *)
        # invalid
        with pytest.raises(ValueError, match="base64url"):
            _check_base64url("AA===")
        with pytest.raises(ValueError, match="base64url"):
            _check_base64url("AA*")
