/**
 * handshake-integration — L4 communication handshake-phase trust-boundary integration
 *
 * Responsibilities:
 * - Establish the trust-boundary during the handshake phase (embedded as handshake middleware)
 * - Verify the trust-boundary is ESTABLISHED before receiving an envelope (otherwise fail-closed reject + TB_SUSPENDED_OPERATION_DENIED)
 * - Implement lease-only renewal (lease renewal → tb LeaseExtensionProof + mandatory csp 5 fields)
 *
 * Design principles:
 * - L4 does not perform csp Ed25519 verify directly (it goes through the BoundaryProofVerifier abstraction, injected by the caller)
 * - It does not modify the existing envelope.ts / handshake/* directly — it provides middleware-style hooks
 * - Anti-phantom: every enforcement path has an active invocation; not a phantom check
 *
 * anti-pattern defenses:
 * - stub default success is not allowed (this middleware fails closed when the verifier is missing / the boundary does not exist)
 * - fail-degraded is not allowed (invariant violation = throw TbProtocolError)
 */

import type { DID, Timestamp } from '@coivitas/types';

import {
    TbProtocolError,
    type TrustBoundary,
    type TrustBoundaryId,
} from './types.js';
import type {
    BoundaryProofVerifier,
    TrustBoundaryLifecycleManager,
    TrustBoundaryStorage,
} from './lifecycle-manager.js';

// ─── handshake-time boundary establishment hook ──────────────────────────────────

/**
 * HandshakeBoundaryContext — handshake middleware context
 *
 * Implements steps 3-4 (the server issues a PoP challenge → principalSide constructs the csp signed payload).
 * The handshake middleware calls this hook to establish the trust-boundary after the responder completes the challenge / response phase.
 */
export interface HandshakeBoundaryContext {
    /** the server-computed trust-boundary registry URL (I7 audience strict equality) */
    readonly expectedAudience: string;
    /** server-issued challenge (I7 replay protection; uses the csp `challenge` field) */
    readonly expectedChallenge: string;
    /** principal-side DID */
    readonly principalSide: DID;
    /** bounded-side DID (agent / resource) */
    readonly boundedSide: DID;
    /** boundary scope (reuses the existing capability; a string array placeholder here) */
    readonly boundaryScope: readonly string[];
    /** the notAfter requested by the client (the server will truncate it to maxLifecycleWindow) */
    readonly requestedNotAfter: string; // ISO 8601
    /** boundary unique id (UUID v4; generated by the caller) */
    readonly boundaryId: string;
}

/**
 * createHandshakeBoundaryMiddleware — factory function; returns a handshake middleware hook
 *
 * Usage pattern:
 * ```
 * const middleware = createHandshakeBoundaryMiddleware({ manager, verifier });
 * // call after the HandshakeResponder completes step 6 (signature verify)
 * const boundary = await middleware.onHandshakeComplete(ctx, bindingProof);
 * // before subsequently receiving an envelope, call middleware.assertBoundaryActive(boundary.id)
 * ```
 *
 * Implements steps 8-9:
 * - csp verify pipeline passes → create the binding proof audit event + update trust_boundaries.state = 'active'
 * - failure → fail-closed reject + TB_* error code
 */
export function createHandshakeBoundaryMiddleware(opts: {
    readonly manager: TrustBoundaryLifecycleManager;
}): HandshakeBoundaryMiddleware {
    return new HandshakeBoundaryMiddlewareImpl(opts.manager);
}

export interface HandshakeBoundaryMiddleware {
    /**
     * Called when the handshake completes — establish the trust-boundary (pending state) + immediately transition to active
     *
     * Flow:
     * 1. Call manager.createBoundary to write the pending state
     * 2. Call manager.transitionState onTrustEstablished to trigger the T1 transition (binding proof verify)
     * 3. Return the final active boundary; throw TbProtocolError on failure
     */
    onHandshakeComplete(
        ctx: HandshakeBoundaryContext,
        bindingProof: {
            readonly cspVersion: string;
            readonly token: string;
            readonly disclosedClaims: readonly string[];
            readonly challenge: string;
            readonly audience: string;
            readonly notAfter: string;
            readonly proofValue: string;
        },
        actorDID: DID,
    ): Promise<TrustBoundary>;

    /**
     * pre-envelope-receive hook — must verify boundary state === 'active'
     *
     * Performs the trust-boundary state verify before an envelope is received.
     * Throws on failure:
     * - TB_BOUNDARY_NOT_FOUND: the boundary does not exist
     * - TB_SUSPENDED_OPERATION_DENIED: the suspended state does not allow envelope receive
     * - TB_BOUNDARY_EXPIRED: the expired / revoked states are not allowed
     * - TB_STATE_INVALID: the pending state (trust establishment not complete) does not allow envelope receive
     */
    assertBoundaryActive(boundaryId: TrustBoundaryId): Promise<TrustBoundary>;

    /**
     * lease renewal hook — implements lease-only renewal
     *
     * Calls manager.transitionState onLeaseExtended; uses a LeaseExtensionProof + mandatory csp 5 fields.
     */
    onLeaseExtension(
        ctx: {
            readonly boundaryId: TrustBoundaryId;
            readonly requestedNotAfter: string;
            readonly expectedAudience: string;
            readonly expectedChallenge: string;
        },
        leaseExtensionProof: {
            readonly cspVersion: string;
            readonly token: string;
            readonly disclosedClaims: readonly string[];
            readonly challenge: string;
            readonly audience: string;
            readonly notAfter: string;
            readonly proofValue: string;
        },
        actorDID: DID,
    ): Promise<TrustBoundary>;
}

class HandshakeBoundaryMiddlewareImpl implements HandshakeBoundaryMiddleware {
    constructor(private readonly manager: TrustBoundaryLifecycleManager) {}

    async onHandshakeComplete(
        ctx: HandshakeBoundaryContext,
        bindingProof: {
            readonly cspVersion: string;
            readonly token: string;
            readonly disclosedClaims: readonly string[];
            readonly challenge: string;
            readonly audience: string;
            readonly notAfter: string;
            readonly proofValue: string;
        },
        actorDID: DID,
    ): Promise<TrustBoundary> {
        // step 1 — createBoundary (pending state)
        // boundary-layer string → Timestamp brand cast (the L4 boundary accepts an external ISO 8601 string;
        // the ISO format is strictly validated by isoToMs inside manager.createBoundary; failure throws TB_LIFECYCLE_INVALID)
        const pending = await this.manager.createBoundary({
            id: ctx.boundaryId,
            principalSide: ctx.principalSide,
            boundedSide: ctx.boundedSide,
            boundaryScope: ctx.boundaryScope,
            requestedNotAfter: ctx.requestedNotAfter as Timestamp,
        });

        // step 2 — T1 onTrustEstablished transition (binding proof verify)
        // bindingProof.notAfter must equal the server-enforced pending.lifecycleWindow.notAfter (I8)
        // if they differ, manager.transitionState throws TB_EXPIRY_CLIENT_CONTROLLED
        const active = await this.manager.transitionState({
            id: pending.id,
            event: 'onTrustEstablished',
            actorDID,
            transitionSource: 'client',
            bindingProof: {
                ...bindingProof,
                notAfter: bindingProof.notAfter as Timestamp,
                boundaryId: pending.id,
            },
            verifyContext: {
                expectedAudience: ctx.expectedAudience,
                expectedChallenge: ctx.expectedChallenge,
            },
        });

        return active;
    }

    async assertBoundaryActive(boundaryId: TrustBoundaryId): Promise<TrustBoundary> {
        const boundary = await this.manager.getCurrent(boundaryId);
        if (!boundary) {
            throw new TbProtocolError(
                'TB_BOUNDARY_NOT_FOUND',
                `boundary ${boundaryId} does not exist; envelope receive rejected`,
            );
        }
        switch (boundary.state) {
            case 'active':
                return boundary;
            case 'pending':
                throw new TbProtocolError(
                    'TB_STATE_INVALID',
                    `boundary ${boundaryId} state = pending (trust establishment not complete); envelope receive rejected`,
                    'I3',
                );
            case 'suspended':
                throw new TbProtocolError(
                    'TB_SUSPENDED_OPERATION_DENIED',
                    `boundary ${boundaryId} state = suspended; envelope receive rejected (awaiting an onResumed or onRevoked / onExpired transition)`,
                );
            case 'revoked':
                throw new TbProtocolError(
                    'TB_BOUNDARY_EXPIRED',
                    `boundary ${boundaryId} state = revoked (terminal); envelope receive rejected`,
                    'I5',
                );
            case 'expired':
                throw new TbProtocolError(
                    'TB_BOUNDARY_EXPIRED',
                    `boundary ${boundaryId} state = expired (terminal); envelope receive rejected`,
                    'I5',
                );
            default: {
                const _exhaustive: never = boundary.state;
                throw new TbProtocolError(
                    'TB_STATE_INVALID',
                    `boundary ${boundaryId} state = ${String(_exhaustive)} is not one of the 5 states`,
                    'I3',
                );
            }
        }
    }

    async onLeaseExtension(
        ctx: {
            readonly boundaryId: TrustBoundaryId;
            readonly requestedNotAfter: string;
            readonly expectedAudience: string;
            readonly expectedChallenge: string;
        },
        leaseExtensionProof: {
            readonly cspVersion: string;
            readonly token: string;
            readonly disclosedClaims: readonly string[];
            readonly challenge: string;
            readonly audience: string;
            readonly notAfter: string;
            readonly proofValue: string;
        },
        actorDID: DID,
    ): Promise<TrustBoundary> {
        // implements lease-only renewal: lease renewal uses T2 onLeaseExtended + mandatory csp 5 fields
        return this.manager.transitionState({
            id: ctx.boundaryId,
            event: 'onLeaseExtended',
            actorDID,
            transitionSource: 'client',
            leaseExtensionProof: {
                ...leaseExtensionProof,
                notAfter: leaseExtensionProof.notAfter as Timestamp,
                boundaryId: ctx.boundaryId,
            },
            requestedNotAfter: ctx.requestedNotAfter as Timestamp,
            verifyContext: {
                expectedAudience: ctx.expectedAudience,
                expectedChallenge: ctx.expectedChallenge,
            },
        });
    }
}

// ─── re-export for one-stop import from communication/src/index.ts ──────────────

export type {
    BoundaryProofVerifier,
    TrustBoundaryStorage,
};
