#!/usr/bin/env tsx
/**
 * generate-hcc-cross-lang-fixtures.ts — cross-lang HCC fixture pipeline (TS Producer)
 *
 * Role
 * ----
 * TypeScript HCC v0.2 (packages/types/src/hash-chain-canonicalize + packages/crypto/...)
 * is the authoritative producer of the cross-lang golden bytes; this script writes out
 * `tests/fixtures/cross-lang/hcc-vectors.json`, which the Python side
 * (packages/sdk-python/tests/hash_chain_canonicalize/test_hcc_cross_lang_fixture.py)
 * consumes to verify byte-level consistency (jcs / SHA-256 / preimage concat order / recursive hash chaining).
 *
 * Usage
 * ----
 *   pnpm hcc:fixtures:regenerate → --regenerate mode: write out hcc-vectors.json
 *   pnpm hcc:fixtures:check → --check mode: compare the existing fixture against a regeneration; diff → exit 1
 *
 * Constraints
 * ----
 * - fail-closed: in --check mode, exit 1 + emit the diff to stderr when the diff is non-empty
 * - determinism: same input, same output (no dependency on crypto.randomUUID / new Date())
 *   - entryId = "0000aaaa-vvvv-4ppp-8nnn-XXXXXXXXXXXX" derived from a SHA-256 truncation of chainIdentityJcs + position
 *   - timestamp = "2026-05-24T00:00:00.000Z" + a per-position second offset
 * - boundary comments are annotated at bytes / hex / string conversion points
 * - anti self-equal: hcc-vectors.json is generated by TS; the Python side reads expected values from the JSON, it does not recompute them
 *
 * Vector set (7 entries)
 * ----------------
 * - V1: single-entry chain (genesis only); chainIdentity = the standard three atp fields
 * - V2: 3-entry chain; same chainIdentity; recursive hash
 * - V3: 5-entry chain; same chainIdentity; multiple payload shapes
 * - V4: 3-entry chain; canonicalPayload contains Unicode CJK + emoji
 * - V5: 4-entry chain; chainIdentity multi-field combination (namespace-only / all fields)
 * - V6: NEGATIVE — mixed chainIdentity (3-entry; identity B grafted onto chain A); the Python side must reject
 * - V7: NEGATIVE — tampered canonicalPayloadHash (3-entry; 1 character of the last entry's hash hex is altered); the Python side must reject
 *
 * Authoritative sources
 * ------
 * - packages/types/src/hash-chain-canonicalize/types.ts (HashChainEntry interface + brand factory)
 * - packages/crypto/src/hash-chain-canonicalize/canonicalize-chain-identity.ts (chainIdentity JCS)
 * - packages/crypto/src/hash-chain-canonicalize/preimage-helpers.ts (concatPreimage + computeHash)
 * - packages/crypto/src/hash-chain-canonicalize/canonicalize-hash-chain-entry.ts (payload JCS)
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
    GENESIS_PREVIOUS_HASH,
    HCC_VERSION_CURRENT,
    toCanonicalPayloadHash,
    toChainIdentityJcs,
    toChainPosition,
    toHashChainEntryId,
    toHccVersionString,
    toPreviousHash,
    type ChainIdentity,
    type HashChainEntry,
    type Timestamp,
} from '@coivitas/types';
import {
    canonicalizeChainIdentity,
    canonicalizeHashChainEntryToString,
    computeCanonicalPayloadHashHex,
    concatPreimage,
} from '@coivitas/crypto';

// ─── Path constants ──────────────────────────────────────────────────────────────

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// scripts/ → sdk/ → packages/ → REPO_ROOT
const REPO_ROOT = resolve(__dirname, '..', '..', '..');
const FIXTURE_OUT_DIR = resolve(REPO_ROOT, 'tests', 'fixtures', 'cross-lang');
const OUT_HCC = resolve(FIXTURE_OUT_DIR, 'hcc-vectors.json');

// ─── Deterministic UUID v4 derivation (counters crypto.randomUUID's non-determinism) ───────────

/**
 * deterministicEntryId — derive a deterministic UUID v4 from (seed, position)
 *
 * Algorithm:
 *   1. SHA-256(seed || ":" || position) → 32 byte digest
 *   2. take the first 16 bytes
 *   3. byte[6] = (byte[6] & 0x0f) | 0x40 (version 4)
 *   4. byte[8] = (byte[8] & 0x3f) | 0x80 (variant 10)
 *   5. format as 8-4-4-4-12 hex
 *
 * Output looks like "a1b2c3d4-e5f6-4789-8abc-def012345678"; passes the toHashChainEntryId factory
 * regex validation (strict UUID v4). Same (seed, position) yields the same output.
 */
function deterministicEntryId(seed: string, position: number): string {
    // boundary: string → UTF-8 bytes → SHA-256 → 16 byte UUID
    const input = `${seed}:${position}`;
    const digest = createHash('sha256').update(input, 'utf-8').digest();
    const uuidBytes = Buffer.from(digest.subarray(0, 16));
    uuidBytes[6] = (uuidBytes[6]! & 0x0f) | 0x40;
    uuidBytes[8] = (uuidBytes[8]! & 0x3f) | 0x80;
    // boundary: bytes → hex → UUID 8-4-4-4-12 format
    const hex = uuidBytes.toString('hex');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20, 32)}`;
}

/**
 * deterministicTimestamp — derive an ISO 8601 UTC timestamp from position
 *
 * Base "2026-05-24T00:00:00.000Z" + a per-position second offset; guarantees a strictly monotonic, non-repeating increase.
 */
function deterministicTimestamp(position: number): Timestamp {
    const base = Date.UTC(2026, 4, 24, 0, 0, 0); // 2026-05-24T00:00:00Z (month 0-indexed)
    const ts = new Date(base + position * 1000).toISOString();
    return ts as Timestamp;
}

// ─── HashChainEntry construction (deterministic throughout; avoids appendHashChainEntry due to its randomUUID) ─

/**
 * buildDeterministicEntry — given (payload, chainIdentity, prevEntry, vectorSeed),
 * construct a HashChainEntry; uses the same algorithm as the write path (canonicalize payload + canonicalize identity
 * + concatPreimage + sha256); ID + timestamp are derived deterministically.
 *
 * Identical algorithm to appendHashChainEntry (preimage = canonicalPayloadBytes || chainIdentityJcsBytes
 * order); the differences are:
 *   - entryId: deterministically derived (vs crypto.randomUUID)
 *   - timestamp: deterministically derived (vs new Date)
 *   - no lastEntry chainIdentity continuity guard (the caller's V6 negative vector needs to construct a mixed chain)
 */
function buildDeterministicEntry(
    payload: Record<string, unknown>,
    chainIdentity: ChainIdentity,
    prevEntry: HashChainEntry | undefined,
    vectorSeed: string,
): HashChainEntry {
    // Step 1: payload JCS canonicalize
    const canonicalPayload = canonicalizeHashChainEntryToString(payload);

    // Step 2: chainIdentity JCS canonicalize → ChainIdentityJcs brand
    const chainIdentityJcsRaw = canonicalizeChainIdentity(chainIdentity);
    const chainIdentityJcs = toChainIdentityJcs(chainIdentityJcsRaw);

    // Step 3: preimage concat (payload bytes || identity bytes)
    const preimage = concatPreimage(canonicalPayload, chainIdentityJcs);

    // Step 4: SHA-256 → canonicalPayloadHash hex (64 lowercase) → brand
    const canonicalPayloadHashHex = computeCanonicalPayloadHashHex(preimage);
    const canonicalPayloadHash = toCanonicalPayloadHash(
        canonicalPayloadHashHex,
    );

    // Step 5: previousHash (genesis = 64 zeros OR prev.canonicalPayloadHash)
    const previousHash =
        prevEntry === undefined
            ? toPreviousHash(GENESIS_PREVIOUS_HASH)
            : toPreviousHash(prevEntry.canonicalPayloadHash);

    // Step 6: chainPosition
    const positionNum =
        prevEntry === undefined ? 0 : prevEntry.chainPosition + 1;
    const chainPosition = toChainPosition(positionNum);

    // Step 7: deterministic entryId + timestamp (distinct from appendHashChainEntry's randomUUID + new Date)
    const entryId = toHashChainEntryId(
        deterministicEntryId(vectorSeed, positionNum),
    );
    const timestamp = deterministicTimestamp(positionNum);
    const hccVersion = toHccVersionString(HCC_VERSION_CURRENT);

    return {
        entryId,
        canonicalPayload,
        canonicalPayloadHash,
        previousHash,
        chainPosition,
        chainIdentity,
        timestamp,
        hccVersion,
    };
}

// ─── Vector definitions (V1-V7) ────────────────────────────────────────────────

interface VectorPayloadSpec {
    payload: Record<string, unknown>;
}

interface VectorSpec {
    id: string;
    description: string;
    chainIdentity: ChainIdentity;
    payloads: VectorPayloadSpec[];
    expected_verify_outcome: 'PASS' | 'REJECT';
    /** On REJECT, the error-message substring the Python side expects (HccError.message contains)*/
    expected_reject_error_substring?: string;
    /** On REJECT, the error code the Python side expects (HccErrorCode)*/
    expected_reject_error_code?: string;
    /** Description of the REJECT-type tampering (which field is mutated)*/
    tamper_description?: string;
    /** V6 mixed-identity: replace the chainIdentity of the Nth entry (0-indexed)*/
    mixed_identity_at?: number;
    mixed_identity_value?: ChainIdentity;
    /** V7 tampered hash: replace the Nth character of the last entry's canonicalPayloadHash with 'f'*/
    tamper_last_hash_char_index?: number;
}

const VECTOR_SPECS: VectorSpec[] = [
    {
        id: 'V1-genesis-only',
        description:
            'V1: single-entry chain (genesis only); chainIdentity = atp all three fields; payload minimal ASCII',
        chainIdentity: {
            chainNamespace: 'atp',
            tenantId: 'tenant-v1-stable',
            auditClass: 'L1',
        },
        payloads: [
            {
                payload: {
                    eventType: 'genesis',
                    actor: 'did:agent:v1-actor',
                    nonce: 'nonce-v1-0',
                },
            },
        ],
        expected_verify_outcome: 'PASS',
    },
    {
        id: 'V2-three-entry-chain',
        description:
            'V2: 3-entry chain; same chainIdentity (policy/tenant-002); payload simple incrementing nonce; recursive hash linking',
        chainIdentity: {
            chainNamespace: 'policy',
            tenantId: 'tenant-002',
            auditClass: 'L2',
        },
        payloads: [
            {
                payload: { event: 'init', step: 0, actor: 'did:agent:v2-a' },
            },
            {
                payload: {
                    event: 'update',
                    step: 1,
                    actor: 'did:agent:v2-a',
                    prevRef: 'step-0',
                },
            },
            {
                payload: {
                    event: 'finalize',
                    step: 2,
                    actor: 'did:agent:v2-a',
                    result: 'ok',
                },
            },
        ],
        expected_verify_outcome: 'PASS',
    },
    {
        id: 'V3-five-entry-chain',
        description:
            'V3: 5-entry chain; same chainIdentity (governance/tenant-003); multiple payload shapes (incl. nested + array)',
        chainIdentity: {
            chainNamespace: 'governance',
            tenantId: 'tenant-003',
            auditClass: 'L3',
        },
        payloads: [
            {
                payload: { kind: 'proposal', id: 'prop-001', votes: [] },
            },
            {
                payload: {
                    kind: 'vote',
                    propId: 'prop-001',
                    voter: 'did:agent:v',
                    weight: 1,
                },
            },
            {
                payload: {
                    kind: 'vote',
                    propId: 'prop-001',
                    voter: 'did:agent:w',
                    weight: 2,
                },
            },
            {
                payload: {
                    kind: 'quorum-reached',
                    propId: 'prop-001',
                    nested: { total: 3, threshold: 3 },
                },
            },
            {
                payload: {
                    kind: 'execute',
                    propId: 'prop-001',
                    actions: ['a1', 'a2'],
                    timestamp_ref: '2026-05-24',
                },
            },
        ],
        expected_verify_outcome: 'PASS',
    },
    {
        id: 'V4-unicode-emoji-payload',
        description:
            'V4: 3-entry chain; canonicalPayload with mixed Unicode CJK + emoji (validates JCS UTF-8 + field code-point ordering)',
        chainIdentity: {
            chainNamespace: 'audit-cn',
            tenantId: 'tenant-004',
            auditClass: 'L2',
        },
        payloads: [
            {
                payload: {
                    描述: '初始事件',
                    actor: 'did:agent:中文',
                    emoji: '🔒',
                },
            },
            {
                payload: {
                    描述: '更新事件',
                    actor: 'did:agent:中文',
                    tags: ['标签一', '标签二', '🚀'],
                },
            },
            {
                payload: {
                    描述: '完成',
                    actor: 'did:agent:中文',
                    summary: '混合 ASCII + CJK + emoji 🎉',
                },
            },
        ],
        expected_verify_outcome: 'PASS',
    },
    {
        id: 'V5-multi-field-identity',
        description:
            'V5: 4-entry chain; chainIdentity multi-field combination (atp/tenant-005/L1); payload with number + null + bool',
        chainIdentity: {
            chainNamespace: 'atp',
            tenantId: 'tenant-005',
            auditClass: 'L1',
        },
        payloads: [
            {
                payload: { status: 'pending', count: 0, active: true },
            },
            {
                payload: {
                    status: 'processing',
                    count: 10,
                    active: true,
                    last_actor: null,
                },
            },
            {
                payload: {
                    status: 'review',
                    count: 25,
                    active: true,
                    last_actor: 'did:agent:reviewer',
                },
            },
            {
                payload: {
                    status: 'done',
                    count: 100,
                    active: false,
                    last_actor: 'did:agent:finalizer',
                },
            },
        ],
        expected_verify_outcome: 'PASS',
    },
    {
        id: 'V6-NEGATIVE-mixed-identity',
        description:
            'V6 NEGATIVE: 3-entry chain; entry[1] chainIdentity differs from entry[0]/entry[2] (identity-rebinding); Python verify_hash_chain must reject',
        chainIdentity: {
            chainNamespace: 'audit-A',
            tenantId: 'tenant-A',
            auditClass: 'L1',
        },
        payloads: [
            { payload: { ev: 'a-0' } },
            { payload: { ev: 'a-1' } },
            { payload: { ev: 'a-2' } },
        ],
        expected_verify_outcome: 'REJECT',
        expected_reject_error_substring: 'mixed-identity',
        expected_reject_error_code: 'HCC_CHAIN_IDENTITY_TAMPERED',
        tamper_description:
            'entry[1].chainIdentity replaced with a different tenant; previousHash linkage preserved (fabricated valid appearance); Python verify must reject via chain-level identity consistency check',
        mixed_identity_at: 1,
        mixed_identity_value: {
            chainNamespace: 'audit-B',
            tenantId: 'tenant-B',
            auditClass: 'L1',
        },
    },
    {
        id: 'V7-NEGATIVE-tampered-hash',
        description:
            'V7 NEGATIVE: 3-entry chain; last entry canonicalPayloadHash char 0 changed to "f" (or incremented); Python verify must reject on hash mismatch',
        chainIdentity: {
            chainNamespace: 'audit-tamper',
            tenantId: 'tenant-007',
            auditClass: 'L2',
        },
        payloads: [
            { payload: { ev: 't-0' } },
            { payload: { ev: 't-1' } },
            { payload: { ev: 't-2' } },
        ],
        expected_verify_outcome: 'REJECT',
        expected_reject_error_substring: 'mismatch',
        expected_reject_error_code: 'HCC_HASH_MISMATCH',
        tamper_description:
            'entry[2].canonicalPayloadHash char 0 flip (0→f / a→b); after Python recompute != stored, reject',
        tamper_last_hash_char_index: 0,
    },
];

// ─── Vector → entries[] + expected[] assembly ─────────────────────────────────

interface VectorFixtureOutput {
    id: string;
    description: string;
    chainIdentity: ChainIdentity;
    entries: HashChainEntry[];
    /** Per-entry concat preimage hex (UTF8 bytes; cross-lang byte-level anchor)*/
    expected_concat_preimage_hex_per_position: string[];
    /** Per-entry canonicalPayloadHash (same value as entry.canonicalPayloadHash; a redundant field so the Python test can verify the hash-computation path independently)*/
    expected_canonical_payload_hash_per_position: string[];
    /** The last entry's canonicalPayloadHash (= entries[-1].canonicalPayloadHash; used as the trusted_checkpoint)*/
    expected_final_hash: string;
    /** PASS / REJECT*/
    expected_verify_outcome: 'PASS' | 'REJECT';
    expected_reject_error_substring?: string;
    expected_reject_error_code?: string;
    tamper_description?: string;
}

function flipHexChar(c: string): string {
    // Simple flip rule: 0↔f, 1↔e, 2↔d, 3↔c, 4↔b, 5↔a, 6↔9, 7↔8 (one-to-one)
    const map: Record<string, string> = {
        '0': 'f',
        '1': 'e',
        '2': 'd',
        '3': 'c',
        '4': 'b',
        '5': 'a',
        '6': '9',
        '7': '8',
        '8': '7',
        '9': '6',
        a: '5',
        b: '4',
        c: '3',
        d: '2',
        e: '1',
        f: '0',
    };
    const out = map[c];
    if (out === undefined) {
        throw new Error(`flipHexChar: unexpected char "${c}"`);
    }
    return out;
}

function buildVectorOutput(spec: VectorSpec): VectorFixtureOutput {
    const entries: HashChainEntry[] = [];
    const expectedPreimages: string[] = [];
    const expectedHashes: string[] = [];

    let prev: HashChainEntry | undefined = undefined;

    for (let i = 0; i < spec.payloads.length; i++) {
        // Decide the chainIdentity used by this entry (V6 mixed-identity switches it at the specified position)
        const usedIdentity =
            spec.mixed_identity_at === i && spec.mixed_identity_value
                ? spec.mixed_identity_value
                : spec.chainIdentity;

        const entry = buildDeterministicEntry(
            spec.payloads[i]!.payload,
            usedIdentity,
            prev,
            spec.id,
        );

        // Compute the preimage hex (used for Python cross-lang verification)
        const identityJcs = canonicalizeChainIdentity(usedIdentity);
        const preimage = concatPreimage(entry.canonicalPayload, identityJcs);
        // boundary: Uint8Array → hex string
        const preimageHex = Array.from(preimage, (b) =>
            b.toString(16).padStart(2, '0'),
        ).join('');

        expectedPreimages.push(preimageHex);
        expectedHashes.push(entry.canonicalPayloadHash);
        entries.push(entry);
        prev = entry;
    }

    // V7 tampered hash: replace the Nth character of the last entry's canonicalPayloadHash
    // Note: expected_canonical_payload_hash_per_position keeps the original correct value (the Python side, recomputing from the preimage, should obtain the original);
    // entries[-1].canonicalPayloadHash is tampered into the flipped value (Python verify should reject because recompute != stored).
    // An additional stored_last_hash_after_tamper field is added so the Python test can compare both directions.
    if (
        spec.expected_verify_outcome === 'REJECT' &&
        spec.tamper_last_hash_char_index !== undefined &&
        entries.length > 0
    ) {
        const idx = spec.tamper_last_hash_char_index;
        const lastEntry = entries[entries.length - 1]!;
        const orig = lastEntry.canonicalPayloadHash;
        const flipped =
            orig.slice(0, idx) + flipHexChar(orig[idx]!) + orig.slice(idx + 1);
        // re-cast via the brand factory (flipped is still 64 lowercase hex, satisfying the pattern)
        const tamperedHash = toCanonicalPayloadHash(flipped);
        const tamperedEntry: HashChainEntry = {
            ...lastEntry,
            canonicalPayloadHash: tamperedHash,
        };
        entries[entries.length - 1] = tamperedEntry;
        // expected_canonical_payload_hash_per_position keeps the original value (the Python preimage→hash verification baseline);
        // entries[i].canonicalPayloadHash is the stored tampered value — verify_hash_chain must reject.
        // (do not change the last entry of expectedHashes — leave it as the "correct" baseline)
    }

    // expected_final_hash semantics: when the chain is valid, the last entry's canonicalPayloadHash (i.e. the preimage recompute result).
    // V1-V5 PASS: entries[-1].canonicalPayloadHash === expectedHashes[-1] (the two are equal).
    // V6 mixed-identity: each entry's hash is itself valid (internally consistent per-entry preimage),
    // it is only the chain-level identity that is inconsistent; expectedHashes[-1] = entries[-1].canonicalPayloadHash.
    // V7 tampered hash: entries[-1].canonicalPayloadHash is the tampered, flipped value,
    // expectedHashes[-1] is the original, correct preimage recompute value (differing by 1 character).
    // This field = "what the last entry's hash should be if the chain were valid".
    return {
        id: spec.id,
        description: spec.description,
        chainIdentity: spec.chainIdentity,
        entries,
        expected_concat_preimage_hex_per_position: expectedPreimages,
        expected_canonical_payload_hash_per_position: expectedHashes,
        expected_final_hash: expectedHashes[expectedHashes.length - 1]!,
        expected_verify_outcome: spec.expected_verify_outcome,
        expected_reject_error_substring: spec.expected_reject_error_substring,
        expected_reject_error_code: spec.expected_reject_error_code,
        tamper_description: spec.tamper_description,
    };
}

function generateHccVectors(): object {
    const vectors = VECTOR_SPECS.map(buildVectorOutput);
    return {
        version: 'v0.2',
        generated_by:
            'packages/sdk/scripts/generate-hcc-cross-lang-fixtures.ts',
        ts_canonicalize_lib: 'canonicalize@2.1.0',
        ts_hash_lib: '@noble/hashes/sha256 (TS HCC v0.2)',
        hcc_version: HCC_VERSION_CURRENT,
        preimage_order:
            'canonicalPayloadBytes || chainIdentityJcsBytes',
        vectors,
    };
}

// ─── Serialize + write / check (same pattern as the existing generate-cross-lang-fixtures.ts) ──

function serializeFixture(data: object): string {
    return JSON.stringify(data, null, 4);
}

function runRegenerate(): void {
    mkdirSync(FIXTURE_OUT_DIR, { recursive: true });
    const out = generateHccVectors();
    writeFileSync(OUT_HCC, serializeFixture(out) + '\n', 'utf-8');
    process.stdout.write(
        `[hcc-fixtures:regenerate] wrote 1 fixture file:\n  ${OUT_HCC}\n` +
            `  vectors: ${VECTOR_SPECS.length}\n` +
            `  hcc_version: ${HCC_VERSION_CURRENT}\n`,
    );
}

function runCheck(): void {
    const expectedContent = serializeFixture(generateHccVectors()) + '\n';

    if (!existsSync(OUT_HCC)) {
        process.stderr.write(
            `[hcc-fixtures:check] FAIL — fixture file missing:\n  ${OUT_HCC}\n` +
                `Run 'pnpm hcc:fixtures:regenerate' and commit the result.\n`,
        );
        process.exit(1);
    }

    const actual = readFileSync(OUT_HCC, 'utf-8');
    if (actual === expectedContent) {
        process.stdout.write(
            '[hcc-fixtures:check] PASS — hcc-vectors.json matches TS output.\n',
        );
        return;
    }

    // line-level diff summary (fail-closed: emit the diff to stderr)
    const actualLines = actual.split('\n');
    const expectedLines = expectedContent.split('\n');
    const maxLen = Math.max(actualLines.length, expectedLines.length);
    const diffLines: string[] = [`DIFF in ${OUT_HCC}:`];
    let diffCount = 0;
    for (let i = 0; i < maxLen && diffCount < 20; i++) {
        const a = actualLines[i] ?? '(missing)';
        const e = expectedLines[i] ?? '(missing)';
        if (a !== e) {
            diffLines.push(`  line ${i + 1}: actual  = ${a}`);
            diffLines.push(`  line ${i + 1}: expected= ${e}`);
            diffCount++;
        }
    }
    if (diffCount >= 20) {
        diffLines.push('  ... (truncated at 20 diff lines)');
    }
    process.stderr.write(
        `[hcc-fixtures:check] FAIL — hcc-vectors.json is stale.\n` +
            `Run 'pnpm hcc:fixtures:regenerate' and commit the updated fixture file.\n\n` +
            diffLines.join('\n') +
            '\n',
    );
    process.exit(1);
}

// ─── Entry point ────────────────────────────────────────────────────

const args = process.argv.slice(2);
if (args.includes('--regenerate')) {
    runRegenerate();
} else if (args.includes('--check')) {
    runCheck();
} else {
    process.stderr.write(
        'Usage: generate-hcc-cross-lang-fixtures.ts --regenerate | --check\n',
    );
    process.exit(1);
}
