import type {
    DID,
    HandshakeAuthorizationValidator,
    Timestamp,
} from '@coivitas/types';

import type { SessionStore } from '../session/types.js';
import type { Transport } from '../transport/types.js';

/**
 * Abstract interface for nonce persistence; the default in-memory implementation lives in responder.ts
 *
 * claim() must be atomic: returns true and records on first sight, returns false if already present.
 * The atomic semantics eliminate the TOCTOU race in multi-worker scenarios (Redis SET NX / PostgreSQL INSERT ON CONFLICT).
 */
export interface NonceStore {
    claim(nonce: string, expiresAt: Date): Promise<boolean>;
}

/**
 * Handshake encryption negotiation preference
 *
 * - OFF: this side does not support encryption, body is plaintext
 * - OPT_IN: this side supports encryption but does not require it
 * - REQUIRED: this side requires encryption, rejects if the peer does not support it
 *
 */
export type EncryptionPreference = 'OFF' | 'OPT_IN' | 'REQUIRED';

/**
 * Negotiated encryption mode (compatibility matrix result)
 */
export type NegotiatedEncryptionMode = 'OFF' | 'REQUIRED';

/**
 * Encryption negotiation parameters within HandshakeChallenge
 *
 * The Initiator carries this structure when declaring OPT_IN or REQUIRED.
 * It is not carried for OFF (the field being absent = legacy non-encrypted behavior).
 *
 */
export interface HandshakeChallengeEncryption {
    /** This side's preference ('OFF' cannot be written explicitly; an absent field is equivalent to OFF)*/
    preference: 'OPT_IN' | 'REQUIRED';
    /** X25519 32B ephemeral public key, hex or base64url*/
    initiatorEphemeralPublicKey: string;
    /** Protocol version identifier*/
    encryptionProtocolVersion: 'ap/e2e/v1';
}

/**
 * Encryption negotiation parameters within HandshakeResponse
 *
 * The Responder carries this structure when the negotiation result is REQUIRED (including responderEphemeralPublicKey).
 * When the negotiation result is OFF, the structure is still carried but responderEphemeralPublicKey does not appear.
 *
 */
export interface HandshakeResponseEncryption {
    /** Negotiation result: OFF or REQUIRED*/
    negotiatedMode: NegotiatedEncryptionMode;
    /** The Responder's own preference*/
    responderPreference: EncryptionPreference;
    /** Appears only when REQUIRED: Responder X25519 32B ephemeral public key*/
    responderEphemeralPublicKey?: string;
    /** Protocol version identifier*/
    encryptionProtocolVersion: 'ap/e2e/v1';
    /**
     * First 16 bytes of transcript_hash in hex (32 hex chars)
     * Used by the Initiator to verify negotiation integrity
     */
    transcriptHashConfirmation: string;
    /**
     * The capabilityTokenFingerprint returned by responder HAV.validate().
     *
     * Conditions for presence (the both-empty-or-both-non-empty contract):
     * - negotiatedMode='REQUIRED' and challenge.capabilityTokenId !== null: required
     * - other scenarios: omitted
     *
     * The Initiator uses this value as the 16th field `authorizedTokenFingerprint` of the
     * transcript_hash to rebuild the local transcript; when absent it falls back to ''
     * (compatible with the negotiatedMode='OFF' or capabilityTokenId === null paths).
     *
     */
    authorizedTokenFingerprint?: string;
}

/**
 * Encrypted session establishment information after the handshake completes (returned to upper layers)
 */
export interface EncryptionHandshakeResult {
    /** Negotiation result*/
    negotiatedMode: NegotiatedEncryptionMode;
    /** Session key material derived via ECDH (non-null only when REQUIRED)*/
    derivedKeys?: {
        initiatorEphemeralPublicKeyHex: string;
        responderEphemeralPublicKeyHex: string;
        transcriptHash: Uint8Array;
    };
}

export interface HandshakeChallenge {
    challengeId: string;
    initiatorDid: DID;
    responderDid: DID;
    /** 32-byte random value (64 hex chars), for replay protection*/
    nonce: string;
    timestamp: Timestamp;
    expiresAt: Timestamp;
    initiatorCapabilities: string[];
    // Capability-token extensions (optional, backward compatible)
    principalDid?: DID;
    capabilityTokenId?: string;
    resumeSessionId?: string;
    /** Encryption negotiation parameters; absent = legacy OFF*/
    encryption?: HandshakeChallengeEncryption;
}

export interface HandshakeResponse {
    challengeId: string;
    /** UUID v4 generated by the Responder*/
    sessionId: string;
    responderDid: DID;
    responderCapabilities: string[];
    /** Must match HandshakeChallenge.nonce*/
    nonce: string;
    timestamp: Timestamp;
    /** Encryption negotiation result; absent = non-encrypted session*/
    encryption?: HandshakeResponseEncryption;
}

export interface HandshakeInitBody {
    challenge: HandshakeChallenge;
}

export interface HandshakeAckBody {
    response: HandshakeResponse;
    accepted: boolean;
    reason?: string;
}

export interface HandshakeResult {
    sessionId: string;
    negotiatedCapabilities: string[];
    /**
     * Encrypted handshake result; non-null only when the negotiation result is REQUIRED
     *
     */
    encryption?: EncryptionHandshakeResult;
}

export interface HandshakeInitiatorOptions {
    initiatorDid: DID;
    initiatorPrivateKey: string;
    transport: Transport;
    /** Resolves a DID public key (used to verify the HANDSHAKE_ACK signature)*/
    resolvePublicKey: (did: DID) => Promise<string | null>;
    /** Challenge expiry duration (ms, default 60_000)*/
    challengeExpiryMs?: number;
    /** The capability set this side declares support for*/
    capabilities?: string[];
    /** Maximum retry count after a handshake timeout (default 2)*/
    maxRetries?: number;
    /**
     * This side's encryption negotiation preference; defaults to OFF (backward compatible with the non-encrypted handshake)
     *
     */
    encryptionPreference?: EncryptionPreference;
}

export interface InitiateParams {
    responderDid: DID;
    responderEndpoint: string;
    /** Timeout for waiting on the ACK (ms, default 30_000)*/
    timeoutMs?: number;
    /**
     * Required for encryption mode REQUIRED: principal DID (equivalent to challenge.principalDid)
     *
     * The original InitiateParams implementation lacked this field, so attemptHandshake
     * never carried principalDid when building the challenge; when either side has encryptionPreference =
     * REQUIRED, the responder throws ENCRYPTION_REQUIRES_CAPABILITY_TOKEN because
     * challenge.capabilityTokenId === null, making the REQUIRED path completely unusable.
     *
     */
    principalDid?: DID;
    /**
     * Required for encryption mode REQUIRED: capability token ID (equivalent to challenge.capabilityTokenId)
     *
     */
    capabilityTokenId?: string;
}

export interface HandshakeResponderOptions {
    responderDid: DID;
    responderPrivateKey: string;
    /** Verifies whether the initiator is allowed to handshake (true = accept, false = reject)*/
    verifyInitiator: (initiatorDid: DID) => Promise<boolean>;
    /** Resolves a DID public key (used to verify the HANDSHAKE_INIT signature)*/
    resolvePublicKey: (did: DID) => Promise<string | null>;
    /** The capability set this side declares support for*/
    capabilities?: string[];
    /** nonce store (replay protection); uses the in-memory implementation by default; Redis/PostgreSQL can be injected in production*/
    nonceStore?: NonceStore;
    // Added (optional — without injection, behavior matches the baseline non-injected handshake)
    sessionStore?: SessionStore;
    authorizationValidator?: HandshakeAuthorizationValidator;
    /**
     * This side's encryption negotiation preference; defaults to OFF (backward compatible with the pre-existing non-encrypted behavior)
     *
     */
    encryptionPreference?: EncryptionPreference;
}
