-- rfp-fixture.sql

-- Resolver Freshness Proof (RFP) v0.1 SQL fixture
-- (for tests + acceptance script)

-- Carries over:
-- - rfp-fixture.json same-source data (JSON for app-layer; SQL for DB-layer)
-- - 6-field schema
-- - 6 fixture scenarios: normal / stale / watermark_regress / sig_invalid /
-- resolver_unknown / quorum_below_threshold

-- Usage:
-- - test setup: after truncating the identity.resolver_freshness_proofs table, run \i rfp-fixture.sql
-- - acceptance script: verify that the CHECK constraints cover all illegal data paths

-- Note:
-- - the signature column uses placeholder base64url strings in the test environment (real signatures are generated by the runtime)
-- - asOfTime is the placeholder '2026-05-18T10:00:00.000Z' (replaced with NOW() in the acceptance script)
-- - this file does not depend on any migration sequence number (standalone fixture DDL)

BEGIN;

-- ─── DDL: resolver_freshness_proofs (acceptance-test only; production follows the identity-layer persistence strategy)

CREATE TABLE IF NOT EXISTS identity.resolver_freshness_proofs (
    id               BIGSERIAL PRIMARY KEY,
    -- 6 fields
    rfp_version      TEXT NOT NULL
                     CHECK (rfp_version ~ '^\d+\.\d+\.\d+$'),
    csp_version      TEXT NOT NULL
                     CHECK (csp_version ~ '^\d+\.\d+\.\d+$'),
    resolver_did     TEXT NOT NULL
                     CHECK (resolver_did LIKE 'did:%'),
    as_of_time       TIMESTAMPTZ NOT NULL,
    freshness_window INTEGER NOT NULL
                     CHECK (freshness_window >= 1000 AND freshness_window <= 3600000),
    signature        TEXT NOT NULL
                     CHECK (signature ~ '^[A-Za-z0-9_-]+$'),
    -- fixture metadata
    scenario_id      TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rfp_resolver_did
    ON identity.resolver_freshness_proofs (resolver_did);

CREATE INDEX IF NOT EXISTS idx_rfp_as_of_time
    ON identity.resolver_freshness_proofs (as_of_time);

-- ─── Cleanup (inter-test isolation) ────────────────────────────────────────────────────

TRUNCATE TABLE identity.resolver_freshness_proofs RESTART IDENTITY CASCADE;

-- ─── Fixture 1: normal_valid (P1 normal path — all 8 invariants pass) ─────────────

INSERT INTO identity.resolver_freshness_proofs (
    rfp_version, csp_version, resolver_did,
    as_of_time, freshness_window, signature, scenario_id
) VALUES (
    '1.0.0',
    '1.0.0',
    'did:agent:resolver-fixture-001',
    NOW(),
    300000,
    -- placeholder signature (replaced in the acceptance script with the real signature produced by createResolverFreshnessProof())
    'PLACEHOLDER_VALID_SIGNATURE_BASE64URL_NORMAL',
    'normal_valid'
);

-- ─── Fixture 2: freshness_stale (P2 I_asof_window fails; RFP_FRESHNESS_EXPIRED; HTTP 503) ──

INSERT INTO identity.resolver_freshness_proofs (
    rfp_version, csp_version, resolver_did,
    as_of_time, freshness_window, signature, scenario_id
) VALUES (
    '1.0.0',
    '1.0.0',
    'did:agent:resolver-fixture-001',
    -- as_of_time is outside the freshnessWindow (5 minutes = 300000ms)
    '2026-05-18T00:00:00.000Z',
    300000,
    'PLACEHOLDER_STALE_PROOF_SIGNATURE_BASE64URL',
    'freshness_stale'
);

-- ─── Fixture 3: watermark_regress (P3 I_ver fails; RFP_VERSION_UNSUPPORTED; HTTP 422) ───

INSERT INTO identity.resolver_freshness_proofs (
    rfp_version, csp_version, resolver_did,
    as_of_time, freshness_window, signature, scenario_id
) VALUES (
    -- rfp_version is not 1.0.0 (the CHECK constraint does not block the semver format; verifyResolverFreshness blocks the semantics)
    '0.9.0',
    '1.0.0',
    'did:agent:resolver-fixture-001',
    NOW(),
    300000,
    'PLACEHOLDER_WATERMARK_REGRESS_SIGNATURE_BASE64URL',
    'watermark_regress'
);

-- ─── Fixture 4: signature_invalid (P4 I_sig fails; RFP_SIGNATURE_INVALID; HTTP 401) ────

INSERT INTO identity.resolver_freshness_proofs (
    rfp_version, csp_version, resolver_did,
    as_of_time, freshness_window, signature, scenario_id
) VALUES (
    '1.0.0',
    '1.0.0',
    'did:agent:resolver-fixture-001',
    NOW(),
    300000,
    -- 87 chars base64url — passes the CHECK constraint format validation, but Ed25519 verifyRfp is guaranteed to fail
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
    'signature_invalid'
);

-- ─── Fixture 5: resolver_unknown (P5 publicKey resolution fails; RFP_SIGNATURE_INVALID; HTTP 401) ─

INSERT INTO identity.resolver_freshness_proofs (
    rfp_version, csp_version, resolver_did,
    as_of_time, freshness_window, signature, scenario_id
) VALUES (
    '1.0.0',
    '1.0.0',
    -- resolver_did is not in any public-key registry → publicKeyResolver.resolvePublicKey() returns null
    'did:agent:resolver-fixture-UNKNOWN-999',
    NOW(),
    300000,
    'PLACEHOLDER_UNKNOWN_RESOLVER_SIGNATURE_BASE64URL',
    'resolver_unknown'
);

-- ─── Fixture 6: quorum_below_threshold (P6 verifyQuorumFreshness fails; RFP_QUORUM_FRESHNESS_UNMET; HTTP 503) ──
-- Note: the quorum aggregation logic is application-layer behavior (verifyQuorumFreshness())
-- The SQL layer only stores each node's proof. This fixture stores the proof of only 1 of 3 valid nodes; the remaining 2 nodes have no records.

-- quorumThreshold = 2; only resolver-node-c has a proof → 1 < 2 → RFP_QUORUM_FRESHNESS_UNMET

INSERT INTO identity.resolver_freshness_proofs (
    rfp_version, csp_version, resolver_did,
    as_of_time, freshness_window, signature, scenario_id
) VALUES (
    '1.0.0',
    '1.0.0',
    'did:agent:resolver-node-c',
    NOW(),
    300000,
    'PLACEHOLDER_QUORUM_NODE_C_SIGNATURE_BASE64URL',
    'quorum_below_threshold'
);
-- resolver-node-a and resolver-node-b: no proof (quorum-shortfall scenario)

COMMIT;
