/**
 * EncryptedBody / MessageReceipt schema + full coverage of the encryption error-code set
 *
 * Coverage:
 * 1. EncryptedBody AJV schema validation (valid + invalid fixtures)
 * 2. MessageReceipt AJV schema validation (valid + invalid fixtures)
 * 3. All 33 encryption error codes are registered in PROTOCOL_ERROR_CODES (runtime + type dual validation)
 */
import { describe, expect, it } from 'vitest';

import type { EncryptedBody, MessageReceipt } from '../encryption.js';
import { ledgerSchema, validateAgainstSchema } from '../index.js';
import type { ProtocolErrorCode } from '../index.js';

// ── Shared fixture constants ─────────────────────────────────────────────────────────

const validEncryptedBodyBusiness: EncryptedBody = {
    encrypted: true,
    encryptionProtocolVersion: 'ap/e2e/v1',
    type: 'BUSINESS',
    ciphertext: 'a'.repeat(64),
    aeadNonce: 'b'.repeat(24),
    keyId: 'c'.repeat(32),
};

const validEncryptedBodyReceipt: EncryptedBody = {
    encrypted: true,
    encryptionProtocolVersion: 'ap/e2e/v1',
    type: 'RECEIPT',
    ciphertext: 'd'.repeat(128),
    aeadNonce: 'e'.repeat(24),
    keyId: 'f'.repeat(32),
    aadSummary: { envelopeId: 'env-001', messageType: 'NEGOTIATION_REQUEST' },
};

const validMessageReceipt: MessageReceipt = {
    // UUID v4 — must satisfy schemas.ts uuidV4Pattern (NegotiationEnvelope.id is generated by randomUUID)
    ackEnvelopeId: '00000000-0000-4000-8000-000000000001',
    sessionId: 'sess-0000-0000-0000-0000',
    paramsHash: 'a'.repeat(64),
    auditIntentId: 'intent-001',
    receivedAt: '2026-05-01T12:00:00.000Z',
    receiptSignature: 'b'.repeat(128),
};

// ── EncryptedBody AJV schema validation ─────────────────────────────────────

describe('EncryptedBody schema validation', () => {
    it('should accept valid EncryptedBody with type=BUSINESS', () => {
        const result = validateAgainstSchema(
            validEncryptedBodyBusiness,
            'encryptedBody',
        );
        expect(result.valid).toBe(true);
        expect(result.errors).toHaveLength(0);
    });

    it('should accept valid EncryptedBody with type=RECEIPT and aadSummary', () => {
        const result = validateAgainstSchema(
            validEncryptedBodyReceipt,
            'encryptedBody',
        );
        expect(result.valid).toBe(true);
        expect(result.errors).toHaveLength(0);
    });

    it('should accept valid EncryptedBody without optional aadSummary', () => {
        const noAad: EncryptedBody = {
            encrypted: true,
            encryptionProtocolVersion: 'ap/e2e/v1',
            type: 'BUSINESS',
            ciphertext: 'a'.repeat(64),
            aeadNonce: 'b'.repeat(24),
            keyId: 'c'.repeat(32),
        };
        const result = validateAgainstSchema(noAad, 'encryptedBody');
        expect(result.valid).toBe(true);
    });

    it('should reject EncryptedBody missing required field: encrypted', () => {
        const { encrypted: _omit, ...noEncrypted } = validEncryptedBodyBusiness;
        const result = validateAgainstSchema(noEncrypted, 'encryptedBody');
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody with encrypted=false (must be const true)', () => {
        const result = validateAgainstSchema(
            { ...validEncryptedBodyBusiness, encrypted: false },
            'encryptedBody',
        );
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody missing required field: encryptionProtocolVersion', () => {
        const { encryptionProtocolVersion: _omit, ...noVersion } =
            validEncryptedBodyBusiness;
        const result = validateAgainstSchema(noVersion, 'encryptedBody');
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody with wrong encryptionProtocolVersion value', () => {
        const result = validateAgainstSchema(
            {
                ...validEncryptedBodyBusiness,
                encryptionProtocolVersion: 'ap/e2e/v2',
            },
            'encryptedBody',
        );
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody missing required field: type', () => {
        const { type: _omit, ...noType } = validEncryptedBodyBusiness;
        const result = validateAgainstSchema(noType, 'encryptedBody');
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody with unknown type value', () => {
        const result = validateAgainstSchema(
            { ...validEncryptedBodyBusiness, type: 'UNKNOWN_TYPE' },
            'encryptedBody',
        );
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody missing required field: ciphertext', () => {
        const { ciphertext: _omit, ...noCiphertext } =
            validEncryptedBodyBusiness;
        const result = validateAgainstSchema(noCiphertext, 'encryptedBody');
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody with empty ciphertext string', () => {
        const result = validateAgainstSchema(
            { ...validEncryptedBodyBusiness, ciphertext: '' },
            'encryptedBody',
        );
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody missing required field: aeadNonce', () => {
        const { aeadNonce: _omit, ...noNonce } = validEncryptedBodyBusiness;
        const result = validateAgainstSchema(noNonce, 'encryptedBody');
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody missing required field: keyId', () => {
        const { keyId: _omit, ...noKeyId } = validEncryptedBodyBusiness;
        const result = validateAgainstSchema(noKeyId, 'encryptedBody');
        expect(result.valid).toBe(false);
    });

    it('should reject EncryptedBody with additional unknown field (additionalProperties: false)', () => {
        const result = validateAgainstSchema(
            {
                ...validEncryptedBodyBusiness,
                unknownField: 'should-be-rejected',
            },
            'encryptedBody',
        );
        expect(result.valid).toBe(false);
    });

    // keyId must be 32 hex or 22 base64url (first 16 bytes of SHA-256, three-state coexistence)
    it('should reject EncryptedBody with malformed keyId (wrong length, not 32-hex/22-base64url)', () => {
        const result = validateAgainstSchema(
            { ...validEncryptedBodyBusiness, keyId: 'abc' },
            'encryptedBody',
        );
        expect(result.valid).toBe(false);
    });

    it('should accept EncryptedBody with base64url-encoded keyId (22 chars, three-state coexistence)', () => {
        // base64url representation of a 16-byte random string, 22 chars, no padding
        const result = validateAgainstSchema(
            {
                ...validEncryptedBodyBusiness,
                keyId: 'AAECAwQFBgcICQoLDA0ODw',
            },
            'encryptedBody',
        );
        expect(result.valid).toBe(true);
    });
});

// ── MessageReceipt AJV schema validation ────────────────────────────────────

describe('MessageReceipt schema validation', () => {
    it('should accept valid MessageReceipt', () => {
        const result = validateAgainstSchema(
            validMessageReceipt,
            'messageReceipt',
        );
        expect(result.valid).toBe(true);
        expect(result.errors).toHaveLength(0);
    });

    it('should reject MessageReceipt missing required field: ackEnvelopeId', () => {
        const { ackEnvelopeId: _omit, ...noAck } = validMessageReceipt;
        const result = validateAgainstSchema(noAck, 'messageReceipt');
        expect(result.valid).toBe(false);
    });

    it('should reject MessageReceipt missing required field: sessionId', () => {
        const { sessionId: _omit, ...noSession } = validMessageReceipt;
        const result = validateAgainstSchema(noSession, 'messageReceipt');
        expect(result.valid).toBe(false);
    });

    it('should reject MessageReceipt missing required field: paramsHash', () => {
        const { paramsHash: _omit, ...noHash } = validMessageReceipt;
        const result = validateAgainstSchema(noHash, 'messageReceipt');
        expect(result.valid).toBe(false);
    });

    it('should reject MessageReceipt missing required field: auditIntentId', () => {
        const { auditIntentId: _omit, ...noIntent } = validMessageReceipt;
        const result = validateAgainstSchema(noIntent, 'messageReceipt');
        expect(result.valid).toBe(false);
    });

    it('should reject MessageReceipt missing required field: receivedAt', () => {
        const { receivedAt: _omit, ...noReceived } = validMessageReceipt;
        const result = validateAgainstSchema(noReceived, 'messageReceipt');
        expect(result.valid).toBe(false);
    });

    it('should reject MessageReceipt with malformed receivedAt timestamp (space separator)', () => {
        const result = validateAgainstSchema(
            { ...validMessageReceipt, receivedAt: '2026-05-01 12:00:00' },
            'messageReceipt',
        );
        expect(result.valid).toBe(false);
    });

    it('should reject MessageReceipt missing required field: receiptSignature', () => {
        const { receiptSignature: _omit, ...noSig } = validMessageReceipt;
        const result = validateAgainstSchema(noSig, 'messageReceipt');
        expect(result.valid).toBe(false);
    });

    it('should reject MessageReceipt with additional unknown field (additionalProperties: false)', () => {
        const result = validateAgainstSchema(
            { ...validMessageReceipt, extraField: 'should-be-rejected' },
            'messageReceipt',
        );
        expect(result.valid).toBe(false);
    });

    // ackEnvelopeId must be a UUID v4 (NegotiationEnvelope.id is generated by randomUUID)
    it('should reject MessageReceipt with non-UUID ackEnvelopeId (cannot reference any envelope)', () => {
        const result = validateAgainstSchema(
            { ...validMessageReceipt, ackEnvelopeId: 'env-ack-001' },
            'messageReceipt',
        );
        expect(result.valid).toBe(false);
    });

    it('should reject MessageReceipt with UUID v1 ackEnvelopeId (must be v4 specifically)', () => {
        // version=1 (note the 13th char is 1 rather than 4)
        const result = validateAgainstSchema(
            {
                ...validMessageReceipt,
                ackEnvelopeId: '00000000-0000-1000-8000-000000000001',
            },
            'messageReceipt',
        );
        expect(result.valid).toBe(false);
    });
});

// ── All 33 encryption error codes registered ────────────────────────────────────────────
// All 33 error codes must be registered in packages/types/src/errors.ts,
// confirmed at runtime via ledgerSchema.$defs.protocolError.properties.code.enum.

describe('encryption error codes registration', () => {
    // All 33 encryption error codes (10 previously registered + 23 new)
    const ss91ErrorCodes: readonly ProtocolErrorCode[] = [
        // Previously registered related error codes (10)
        'DECRYPTION_FAILED',
        'REKEY_FAILED',
        'ENCRYPTION_REQUIRED',
        'ENCRYPTION_REQUIRES_CAPABILITY_TOKEN',
        'INVALID_ENCRYPTED_BODY',
        'INVALID_ENCRYPTION_OFFER',
        'SESSION_HANDLE_REVOKED',
        'UNEXPECTED_RECEIPT_FOR_RECEIPT',
        // New (23).
        // Excludes DISCOVERY_NOT_SUPPORTED / DISCOVERY_TARGET_MISMATCH (these belong to the discovery channel, not the encryption error-code set),
        // includes TOKEN_REVOKED + SESSION_TOKEN_MISMATCH.
        'ENCRYPTION_UNSUPPORTED',
        'KEY_AGREEMENT_FAILED',
        'AEAD_NONCE_REUSED',
        'ENCRYPTED_REPLAY_DETECTED',
        'REKEY_REJECTED_BY_AUTHORIZATION',
        'ENCRYPTION_DOWNGRADE_DETECTED',
        'EPHEMERAL_KEY_INVALID',
        'TOKEN_REVOKED',
        'RECEIPT_REQUIRED',
        'RECEIPT_VERIFICATION_FAILED',
        'RECEIPT_SIGNATURE_INVALID',
        'RECEIPT_ENVELOPE_MISMATCH',
        'RECEIPT_SESSION_MISMATCH',
        'RECEIPT_PARAMS_HASH_MISMATCH',
        'RECEIPT_STALE',
        'RECEIPT_TIMEOUT',
        'SESSION_TOKEN_MISMATCH',
        'RECEIPT_SHAPE_WITHOUT_RECEIPT_TYPE',
        'INVALID_RECEIPT_PAYLOAD',
        'CRYPTO_STATE_LOST',
        'AUDIT_INTENT_PERSIST_FAILED',
        'AUDIT_INTENT_TIMEOUT',
        'AUDIT_RECORD_UPDATE_FAILED',
        'POLICY_REQUIRES_OUTBOX',
        'ENCRYPTION_MIRROR_PROOF_UNAVAILABLE',
    ] as const;

    it('should have exactly 33 encryption error codes enumerated (sanity guard)', () => {
        expect(ss91ErrorCodes).toHaveLength(33);
    });

    // ledgerSchema.$defs.protocolError.properties.code.enum is the runtime mirror of PROTOCOL_ERROR_CODES.
    const protocolErrorDef = (
        ledgerSchema as unknown as {
            $defs?: {
                protocolError?: {
                    properties?: {
                        code?: { type?: string; enum?: readonly string[] };
                    };
                };
            };
        }
    ).$defs?.protocolError;

    it('ledgerSchema.$defs.protocolError.properties.code.enum is accessible', () => {
        expect(protocolErrorDef).toBeDefined();
        const codeEnum = protocolErrorDef?.properties?.code?.enum;
        expect(Array.isArray(codeEnum)).toBe(true);
        expect((codeEnum ?? []).length).toBeGreaterThan(50);
    });

    it.each(ss91ErrorCodes)(
        'should include %s in PROTOCOL_ERROR_CODES (via ledgerSchema runtime mirror)',
        (code) => {
            const codeEnum = protocolErrorDef?.properties?.code?.enum ?? [];
            expect(
                codeEnum.includes(code),
                `${code} must be registered in PROTOCOL_ERROR_CODES`,
            ).toBe(true);
        },
    );
});
