-- 007-create-policy-change-records.sql -- standalone Policy change audit table

-- Design:
-- - Standalone table (does not reuse action_records), avoiding extension of the frozen ActionVocabulary enum.
-- - append-only constraint (BEFORE trigger forbids UPDATE / DELETE).
-- - hash chain: row_hash = SHA-256(prev_row_hash || record_id || action_type || agent_did || created_at)
-- computed by the application layer (PolicyChangeRecorder); the DB only stores it.
-- - Idempotent write: record_id UNIQUE prevents duplicate INSERT.
-- - The transaction-level advisory lock (hashtext(agent_did)) is the application layer's responsibility; the DB layer does not enforce it.

-- 3 action types (control plane): POLICY_CREATED | POLICY_UPDATED | POLICY_REVOKED

CREATE SCHEMA IF NOT EXISTS policy;

CREATE TABLE IF NOT EXISTS policy.policy_change_records (
    -- Auto-increment primary key (monotonic, used for hash-chain ordering + chain-head queries)
    id                  BIGSERIAL PRIMARY KEY,

    -- Idempotency identifier (UUID v4 or rec-{uuid}, generated by the application layer)
    record_id           TEXT NOT NULL,

    -- Policy owner agent DID
    agent_did           TEXT NOT NULL,

    -- The principal DID that performed the change (administrator / operator)
    principal_did       TEXT NOT NULL,

    -- Control-plane action type (3 values, orthogonal to the frozen ACTION_VOCABULARY)
    action_type         TEXT NOT NULL,

    -- Policy change parameters (PolicyChangeParams, JSON format)
    -- Contains: policyId, policyVersion, changeType, changedFields?, revokedAt?
    params              JSONB NOT NULL,

    -- hash chain: current row hash (computed by the application layer, hex or base64url encoded)
    row_hash            TEXT NOT NULL,

    -- hash chain: previous row hash (first row = SHA-256(''), i.e. the SHA-256 hex of '')
    prev_row_hash       TEXT NOT NULL,

    -- actor signature (the policy operator's private-key signature over unsignedPayload)
    actor_signature     TEXT NOT NULL,

    -- ledger signature (the ledger private-key signature over unsignedPayload, used as proof of authority)
    ledger_signature    TEXT NOT NULL,

    -- Write timestamp (application layer passes ISO-8601, stored as TIMESTAMPTZ)
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Constraint: record_id globally unique (idempotency + prevents duplicate audit records)
    CONSTRAINT uq_policy_change_records_record_id UNIQUE (record_id),

    -- Constraint: action_type allows only the 3 control-plane values
    CONSTRAINT ck_policy_change_records_action_type
        CHECK (action_type IN ('POLICY_CREATED', 'POLICY_UPDATED', 'POLICY_REVOKED'))
);

-- Index: query the chain by agent_did + hash-chain verification (id ASC guarantees chain order)
CREATE INDEX IF NOT EXISTS idx_policy_change_records_agent_did
    ON policy.policy_change_records (agent_did, id ASC);

-- Index: query the change actor by principal_did
CREATE INDEX IF NOT EXISTS idx_policy_change_records_principal_did
    ON policy.policy_change_records (principal_did);

-- Index: query a time range by created_at
CREATE INDEX IF NOT EXISTS idx_policy_change_records_created_at
    ON policy.policy_change_records (created_at);

-- Index: query a specific change type by action_type
CREATE INDEX IF NOT EXISTS idx_policy_change_records_action_type
    ON policy.policy_change_records (action_type);

-- append-only constraint: BEFORE trigger forbids UPDATE (tamper-proof audit requirement)
CREATE OR REPLACE FUNCTION policy.policy_change_records_immutable()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'policy_change_records is append-only: % not allowed',
        TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

-- Forbid UPDATE
DROP TRIGGER IF EXISTS trg_policy_change_records_no_update ON policy.policy_change_records;
CREATE TRIGGER trg_policy_change_records_no_update
    BEFORE UPDATE ON policy.policy_change_records
    FOR EACH ROW
    EXECUTE FUNCTION policy.policy_change_records_immutable();

-- Forbid DELETE
DROP TRIGGER IF EXISTS trg_policy_change_records_no_delete ON policy.policy_change_records;
CREATE TRIGGER trg_policy_change_records_no_delete
    BEFORE DELETE ON policy.policy_change_records
    FOR EACH ROW
    EXECUTE FUNCTION policy.policy_change_records_immutable();

-- Table comment
COMMENT ON TABLE policy.policy_change_records IS
    'Standalone Policy change audit table (append-only, tamper-evidence hash chain).'
    'See the policy change audit spec. Pre-allocated migration number 007.'
    'Control-plane actions POLICY_CREATED/UPDATED/REVOKED do not enter the frozen action_records.action enum.';
