-- 011_arbitration_records.sql -- operator arbitration records table

-- Governor lane full protocol: persisted arbitration state machine.
-- Pre-allocated number 011.

-- Design:
-- - An arbitration record corresponds to the operator-intervention flow for a SESSION_SUPERSEDED event
-- - half-committed defense: a UNIQUE INDEX ensures that the same relatedRecordId
-- has at most one row in ARBITRATED_PENDING_OPERATOR state
-- - State transition: ARBITRATED_PENDING_OPERATOR -> ARBITRATED (terminal)

-- Created inside the policy schema (same schema as action_records, audit_side_table)
CREATE TABLE IF NOT EXISTS policy.arbitration_records (
    -- UUID primary key (generated by the application layer to ensure global uniqueness)
    id              UUID PRIMARY KEY,

    -- The associated SESSION_SUPERSEDED recordId
    related_record_id   TEXT NOT NULL,

    -- Arbitration state (CHECK constraint allows only valid state values)
    state           TEXT NOT NULL
                        CHECK (state IN ('ARBITRATED_PENDING_OPERATOR', 'ARBITRATED')),

    -- Arbitration reason description
    reason          TEXT NOT NULL,

    -- Creation time
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Operator verdict (JSONB, populated only in the ARBITRATED state)
    verdict         JSONB NULL,

    -- State-update time (populated only in the ARBITRATED state)
    updated_at      TIMESTAMPTZ NULL
);

-- Index: lookup by related_record_id (high-frequency path for state queries)
CREATE INDEX IF NOT EXISTS idx_arbitration_records_related_record_id
    ON policy.arbitration_records (related_record_id);

-- Index: lookup by state (entry point for operator batch processing)
CREATE INDEX IF NOT EXISTS idx_arbitration_records_state
    ON policy.arbitration_records (state, created_at ASC);

-- half-committed defense (F2-recur design):
-- the same relatedRecordId may have at most one row in ARBITRATED_PENDING_OPERATOR state.
-- Combined with application-layer ON CONFLICT DO NOTHING, this forms two layers of defense (first-line DB + second-line application layer).
CREATE UNIQUE INDEX IF NOT EXISTS uniq_arbitration_pending_per_record
    ON policy.arbitration_records (related_record_id)
    WHERE state = 'ARBITRATED_PENDING_OPERATOR';

-- Comment
COMMENT ON TABLE policy.arbitration_records IS
    'Operator arbitration records table, persisting the governor lane SESSION_SUPERSEDED arbitration flow.'
    'half-committed defense: uniq_arbitration_pending_per_record UNIQUE INDEX.';

COMMENT ON COLUMN policy.arbitration_records.verdict IS
    'JSONB operator verdict; populated only in the ARBITRATED state. Contains operatorDid/decision/rationale/timestamp.';
