-- 023_revocation_records.sql -- RevocationList persistence-layer table

-- Full RevocationList implementation (closes out the earlier stub).
-- Pre-allocated number 023.

-- Design:
-- - SPECV-01 v0.4.0 wire format: list_version INT NOT NULL (monotonic)
-- - issuer_signature_payload JSONB: the signed payload including listVersion (JCS RFC 8785)
-- - tenant_id TEXT NOT NULL: strong multi-tenant isolation (all queries MUST filter on it up front)
-- - UNIQUE INDEX: (tenant_id, token_id) guarantees idempotency (REVOCATION_DUPLICATE dedup)
-- - UNIQUE INDEX: (tenant_id, list_id, list_version) guarantees listVersion is monotonically unique
-- - Indexes cover the high-frequency query paths: isRevoked + getRevocations pagination

-- Created inside the policy schema (same schema as action_records, audit_side_table, arbitration_records)
CREATE TABLE IF NOT EXISTS policy.revocation_records (
    -- UUID primary key (generated by the application layer to ensure global uniqueness)
    id                          UUID PRIMARY KEY,

    -- Tenant ID (strong multi-tenant isolation; all queries MUST carry this field)
    tenant_id                   TEXT NOT NULL,

    -- The revoked credential/token ID
    token_id                    TEXT NOT NULL,

    -- The principal DID that performed the revocation (audit accountability)
    revoked_by                  TEXT NOT NULL,

    -- Revocation timestamp (DB server-side time; client overrides are not allowed)
    revoked_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Revocation reason (CHECK constraint allows only valid enum values; fail-closed: invalid values are rejected by the DB)
    reason                      TEXT NOT NULL DEFAULT 'UNSPECIFIED'
                                    CHECK (reason IN (
                                        'KEY_COMPROMISE',
                                        'AFFILIATION_CHANGED',
                                        'SUPERSEDED',
                                        'CESSATION_OF_OPERATION',
                                        'PRIVILEGE_WITHDRAWN',
                                        'UNSPECIFIED'
                                    )),

    -- Revocation list ID (a single tenant may have multiple revocation lists)
    list_id                     TEXT NOT NULL,

    -- Revocation-list monotonically increasing version number (added in v0.4.0)
    -- Incremented by 1 each time a revocation record is written to (tenant_id, list_id); initial value 1.
    -- CHECK constraint: >= 1 (generated by the application layer, double-validated by the DB)
    list_version                INT NOT NULL CHECK (list_version >= 1),

    -- The issuerSignature signed payload (JSONB; includes listVersion)
    -- JCS RFC 8785 canonical serialization; null = no signature (test scenario or deferred signing)
    issuer_signature_payload    JSONB NULL
);

-- ============================================================================
-- Indexes
-- ============================================================================

-- High-frequency query path 1: isRevoked() query (exact tenant + token match)
-- Also serves as the idempotent-dedup UNIQUE INDEX (the REVOCATION_DUPLICATE error-code trigger point)
CREATE UNIQUE INDEX IF NOT EXISTS uniq_revocation_records_tenant_token
    ON policy.revocation_records (tenant_id, token_id);

-- High-frequency query path 2: listVersion monotonic uniqueness (concurrent-write conflict defense)
-- Ensures list_version is not duplicated within a single (tenant_id, list_id)
CREATE UNIQUE INDEX IF NOT EXISTS uniq_revocation_records_list_version
    ON policy.revocation_records (tenant_id, list_id, list_version);

-- Query path 3: getRevocations() pagination (ordered by revoked_at DESC)
CREATE INDEX IF NOT EXISTS idx_revocation_records_tenant_revoked_at
    ON policy.revocation_records (tenant_id, revoked_at DESC);

-- Query path 4: filter by list_id (getRevocations queries by list)
CREATE INDEX IF NOT EXISTS idx_revocation_records_tenant_list_id
    ON policy.revocation_records (tenant_id, list_id);

-- ============================================================================
-- Table comments
-- ============================================================================

COMMENT ON TABLE policy.revocation_records IS
    'RevocationList persistence-layer table.'
    'wire format: list_version INT NOT NULL (monotonic).'
    'multi-tenant: tenant_id NOT NULL, all queries MUST filter on it up front.';

COMMENT ON COLUMN policy.revocation_records.list_version IS
    'SPECV-01 v0.4.0: revocation-list monotonically increasing version number.'
    'Incremented by 1 each time a revocation record is written to (tenant_id, list_id); initial value 1.'
    'The uniq_revocation_records_list_version UNIQUE INDEX guarantees monotonic uniqueness.';

COMMENT ON COLUMN policy.revocation_records.issuer_signature_payload IS
    'SPECV-01 v0.4.0: the issuerSignature signed payload (JSONB).'
    'Includes listVersion; the signature uses JCS RFC 8785 canonical serialization.'
    'null = no signature (test scenario).';

COMMENT ON COLUMN policy.revocation_records.tenant_id IS
    'Strong multi-tenant isolation field. All queries MUST carry this field as an up-front filter condition.'
    'The uniq_revocation_records_tenant_token UNIQUE INDEX includes this field.';
