-- 026_atp_audit_events.sql -- audit-tamper-proof audit_events table (multi-tenant audit isolation)

-- Design principles (fail-closed + multi-tenant isolation + three-way reconciliation):
-- - audit_events is a standalone table (atp v0.1 scope; does not ALTER the existing events table)
-- - tenant_id NOT NULL FK REFERENCES managed_service.tenants(id) ON DELETE RESTRICT
-- ( CASCADE → RESTRICT; prevents cascade erasure of audit history)
-- - audit_class CHECK ∈ ('L1','L2','L3') (per-class independent hash chain)
-- - tamper_proof_hash CHAR(64) CHECK hex (I7 invariant; all 10 fields bound)
-- - previous_hash CHAR(64) NULL (GENESIS = null; non-GENESIS must be non-null; I8 invariant)
-- - timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW() (server-side NOW(); client values not accepted)
-- - composite index (tenant_id, audit_class, created_at DESC) (fetchLastTamperProofHash composite key)
-- - APPEND-ONLY constraint (no UPDATE / DELETE trigger; audit immutability; inherits the audit_side_table pattern)

-- Anti-hard-delete guard:
-- - ON DELETE RESTRICT forces tenants to empty their owned audit_events before deletion
-- - the audit_events table has no DELETE trigger / RLS DELETE permission → events cannot be emptied
-- - result: tenant hard-delete permanently fails (atp v0.1); only tenant soft-delete is supported
-- (reuses the existing status enum 'ACTIVE'/'SUSPENDED'/'DELETED' from 008-create-managed-service-tenants.sql)
-- - the full archive/tombstone offboarding workflow is deferred to atp v0.2 as separate work (out of v0.1 scope)

-- multi-tenant audit isolation

-- (tenants main-table FK anchor) + 010_audit_side_table.sql (inherits the hash chain pattern)

-- pgcrypto: gen_random_uuid() dependency
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Main table: managed_service.audit_events (atp v0.1, 12 fields; standalone table; does not ALTER the existing events table)
CREATE TABLE IF NOT EXISTS managed_service.audit_events (
    -- 12 mandatory fields (11 required + 1 optional signature)

    -- atpVersion: AtpVersionString brand (v0.1 only "1.0.0"; CHECK semver)
    atp_version       TEXT NOT NULL DEFAULT '1.0.0'
        CONSTRAINT chk_audit_events_atp_version_semver
        CHECK (atp_version ~ '^[0-9]+\.[0-9]+\.[0-9]+$'),

    -- eventId: UUID v4 PRIMARY KEY (generated by gen_random_uuid(); client-side values not accepted)
    event_id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- tenantId: TenantId brand (UUID v4 enforced non-null; FK added later)
    tenant_id         UUID NOT NULL,

    -- auditClass: AuditClass brand (CHECK ∈ L1/L2/L3; per-class independent hash chain)
    audit_class       TEXT NOT NULL
        CONSTRAINT chk_audit_events_audit_class
        CHECK (audit_class IN ('L1', 'L2', 'L3')),

    -- actorDid: DID brand (did:* prefix; CHECK LIKE)
    actor_did         TEXT NOT NULL
        CONSTRAINT chk_audit_events_actor_did_prefix
        CHECK (actor_did LIKE 'did:%'),

    -- action: AuditAction brand (length [1, 256])
    action            TEXT NOT NULL
        CONSTRAINT chk_audit_events_action_len
        CHECK (length(action) > 0 AND length(action) <= 256),

    -- target: string (may be an empty string but the field is mandatory)
    target            TEXT NOT NULL DEFAULT '',

    -- canonicalPayload: string (after RFC 8785 JCS canonicalize; empty not accepted)
    canonical_payload TEXT NOT NULL
        CONSTRAINT chk_audit_events_canonical_payload_not_empty
        CHECK (length(canonical_payload) > 0),

    -- tamperProofHash: AuditEventHash brand (SHA-256 hex 64 char; I7 invariant)
    tamper_proof_hash CHAR(64) NOT NULL
        CONSTRAINT chk_audit_events_tamper_proof_hash_hex
        CHECK (tamper_proof_hash ~ '^[0-9a-f]{64}$'),

    -- previousHash: AuditEventHash | null (GENESIS = null; non-GENESIS must be non-null; I8 invariant)
    previous_hash     CHAR(64)
        CONSTRAINT chk_audit_events_previous_hash_hex
        CHECK (previous_hash IS NULL OR previous_hash ~ '^[0-9a-f]{64}$'),

    -- timestamp: Timestamp brand (ISO 8601 UTC; server-side NOW() default)
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- signature: Signature | null (v0.1 optional; Ed25519 base64url format)
    signature         TEXT
        CONSTRAINT chk_audit_events_signature_b64url
        CHECK (signature IS NULL OR signature ~ '^[A-Za-z0-9_-]+=*$')
);

-- Composite index: per-(tenantId, audit_class, created_at DESC) (
-- a perfect match for the fetchLastTamperProofHash + fetchAllEvents query paths)
CREATE INDEX IF NOT EXISTS ix_audit_events_tenant_class_created
    ON managed_service.audit_events (tenant_id, audit_class, created_at DESC);

-- Auxiliary index: actor_did (for downstream actor-perspective consumers such as audit-share)
CREATE INDEX IF NOT EXISTS ix_audit_events_actor_did_created
    ON managed_service.audit_events (actor_did, created_at DESC);

-- Table comment (A41 three-way reconciliation documentation)
COMMENT ON TABLE managed_service.audit_events IS
    'audit-tamper-proof audit_events table.'
    'APPEND-ONLY (audit immutability; no UPDATE / DELETE trigger).'
    'Does not support tenant hard-delete; only tenant soft-delete'
    '(reuses the existing status enum from 008-create-managed-service-tenants.sql; tenants.status = ''DELETED'').';

COMMENT ON COLUMN managed_service.audit_events.tenant_id IS
    'multi-tenant audit isolation.'
    'FK → managed_service.tenants(id) ON DELETE RESTRICT (added after backfill completes).'
    'cross-tenant writes forbidden (application-layer assertTenantScope guard).'
    'high-frequency query path: composite index (tenant_id, audit_class, created_at DESC).';

COMMENT ON COLUMN managed_service.audit_events.tamper_proof_hash IS
    'SHA-256(JCS canonicalize({atpVersion, eventId, tenantId, auditClass, actorDid'
    'action, target, canonicalPayload, previousHash, timestamp})) hex 64 char.'
    'all 10 fields bound (if a DBA changes any one metadata field →'
    'the recomputed hash does not match → tamper detected; the old 3-field pattern sha256(canonicalPayload || previousHash || tenantId) is strictly forbidden).';

COMMENT ON COLUMN managed_service.audit_events.previous_hash IS
    'per-audit_class independent hash chain.'
    'GENESIS state (the chain''s first event) = NULL; non-GENESIS state must be non-NULL.'
    'I8 invariant: per-audit_class scope (tenant_id, audit_class) independent chain'
    'cross-tenant chain-splicing attack defense (writer/verifier share the (tenantId, audit_class) scope).';

COMMENT ON COLUMN managed_service.audit_events.signature IS
    'Optional Ed25519 signature (the second piece of cryptographic tamper-proofing).'
    'v0.1 optional; the v0.1 verifier does not implement real Ed25519 verify (signature !== null → AUDIT_EVENT_SIGNATURE_INVALID; fail-closed).'
    'Real Ed25519 verify is deferred to the atp v0.2 / audit-share L3 phase.';

-- =====================================================================
-- schema_migrations version record (inherits the 023 pattern)
-- =====================================================================
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name = 'schema_migrations'
    ) THEN
        INSERT INTO schema_migrations (version, applied_at)
        VALUES ('026_atp_audit_events', NOW())
        ON CONFLICT (version) DO NOTHING;
    END IF;
END $$;
