"""TS <-> Python Ed25519 signature interop verification (interop contract 1).

TS source of truth
------------------
- TS implementation: ``packages/crypto/src/signing.ts`` ``sign`` / ``verify`` (@noble/curves)
- Test vectors: ``tests/fixtures/conformance/identity/crypto-signing.json`` (RFC 8032)

Cross-language alignment contract
---------------------------------
1. A byte sequence signed by TS with @noble/curves -> Python ``cryptography`` verify PASS
2. Python ``cryptography`` rejects the tampered signatures TS rejects (same key, same message)
3. Public-key encoding compatibility: hex64 (v0.1.0/v0.2.0) + base64url43 (v0.3.0)

Anti self-equal
---------------
The public-key / signature bytes come from the RFC 8032 standard + the TS-side
fixture (not generated by Python verifying itself); ``_crypto.verify_ed25519``
calls the ``cryptography`` library directly (not a mock).
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

import pytest

from coivitas._crypto import CryptoError, verify_ed25519
from coivitas._wire import from_base64url, from_hex, to_base64url

# fixture root (same source as conformance; the single source of truth)
_REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
FIXTURE_PATH = (
    _REPO_ROOT / "tests" / "fixtures" / "conformance" / "identity"
    / "crypto-signing.json"
)


def _load_signing_fixture() -> dict:
    """Load the RFC 8032 + TS-shared Ed25519 test vectors."""
    with FIXTURE_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


class TestEd25519SignatureRfc8032Verify:
    """RFC 8032 standard vectors: Python verify behaves identically to TS verify."""

    def test_valid_rfc8032_signature_verifies_ok(self) -> None:
        """Corresponds to ``crypto-signing.json valid[0]``: RFC 8032 empty-message vector."""
        fixture = _load_signing_fixture()
        valid_samples = fixture["valid"]
        assert len(valid_samples) > 0, "guard against silent skip"

        for sample in valid_samples:
            sample_id = sample["id"]
            public_key = sample["publicKey"]  # hex64
            message_hex = sample["messageHex"]
            signature = sample["signature"]  # hex128

            message = from_hex(message_hex)
            # Path equivalent to TS verify(publicKey, message, signature)
            result = verify_ed25519(public_key, message, signature)
            assert result is True, (
                f"RFC 8032 sample {sample_id} verify=False; "
                f"pk={public_key} msg_hex={message_hex!r} sig={signature}"
            )

    def test_tampered_signature_rejected(self) -> None:
        """Corresponds to ``crypto-signing.json invalid[0]``: tampered signature (first byte changed)."""
        fixture = _load_signing_fixture()
        invalid_samples = fixture["invalid"]
        assert len(invalid_samples) > 0

        for sample in invalid_samples:
            sample_id = sample["id"]
            public_key = sample["publicKey"]
            message_hex = sample.get("messageHex", "")
            signature = sample["signature"]

            message = from_hex(message_hex)
            result = verify_ed25519(public_key, message, signature)
            assert result is False, (
                f"tampered sample {sample_id} unexpectedly verifies=True; "
                f"pk={public_key} sig={signature}"
            )


class TestEd25519PublicKeyEncodingInterop:
    """v0.1.0/v0.2.0 hex and v0.3.0 base64url encoding interop (three-way coexistence)."""

    def test_hex_and_base64url_same_key_verify_same(self) -> None:
        """The same public key should verify identically under hex64 and base64url43 encoding (matches TS detectEncoding)."""
        fixture = _load_signing_fixture()
        valid_samples = fixture["valid"]

        for sample in valid_samples:
            public_key_hex = sample["publicKey"]  # hex64
            message = from_hex(sample["messageHex"])
            signature_hex = sample["signature"]

            # hex encoding: hex -> bytes -> base64url (RFC 4648 no padding)
            pk_bytes = from_hex(public_key_hex)
            public_key_b64url = to_base64url(pk_bytes)
            assert len(public_key_b64url) == 43, (
                f"Ed25519 pk base64url should be 43 chars, got {len(public_key_b64url)}"
            )

            # Both encodings should decode consistently via the _decode_key_or_signature path -> verify True
            r_hex = verify_ed25519(public_key_hex, message, signature_hex)
            r_b64url = verify_ed25519(public_key_b64url, message, signature_hex)
            assert r_hex == r_b64url == True, (
                f"hex/base64url verify mismatch: hex={r_hex} b64url={r_b64url}"
            )

    def test_signature_hex_and_base64url_interop(self) -> None:
        """The signature likewise supports both hex128 / base64url86 encodings."""
        fixture = _load_signing_fixture()
        sample = fixture["valid"][0]
        public_key = sample["publicKey"]
        message = from_hex(sample["messageHex"])
        signature_hex = sample["signature"]

        sig_bytes = from_hex(signature_hex)
        signature_b64url = to_base64url(sig_bytes)
        assert len(signature_b64url) == 86, (
            f"Ed25519 sig base64url should be 86 chars, got {len(signature_b64url)}"
        )

        assert verify_ed25519(public_key, message, signature_hex) is True
        assert verify_ed25519(public_key, message, signature_b64url) is True


class TestEd25519FailClosed:
    """fail-closed: malformed input (not 32/64 bytes) -> CryptoError."""

    def test_short_public_key_raises(self) -> None:
        # hex16 = 8 bytes; not an Ed25519 public-key length
        with pytest.raises(CryptoError, match="32 bytes"):
            verify_ed25519("0123456789abcdef", b"msg", "00" * 64)

    def test_short_signature_raises(self) -> None:
        # hex32 = 16 bytes; not an Ed25519 signature length
        with pytest.raises(CryptoError, match="64 bytes"):
            verify_ed25519("00" * 32, b"msg", "01" * 16)

    def test_invalid_hex_input_raises(self) -> None:
        # Contains non-hex characters
        with pytest.raises(CryptoError):
            verify_ed25519("zz" * 32, b"msg", "00" * 64)

    def test_message_must_be_bytes(self) -> None:
        with pytest.raises(CryptoError, match="bytes-like"):
            verify_ed25519("00" * 32, "not-bytes", "00" * 64)  # type: ignore[arg-type]


class TestEd25519BindingProofFixtureInterop:
    """Cross-language verification of the real signatures in binding-proof.json (principal_key signs the binding content).

    Aligned with TS ``packages/identity/src/binding-proof.ts:verifyBinding`` at the
    verify byte level: principalPublicKey + message bytes + signature -> True/False.
    """

    def test_valid_binding_signature_verifies(self) -> None:
        """binding-rfc-vector: principal-key signs the canonicalized byte sequence of
        (principalDid, agentDid, issuedAt, expiresAt); the signature should verify
        with cryptography.

        This test does **not** reproduce the internal logic of TS verifyBinding; it
        only asserts that the signature in the fixture was produced with the
        corresponding principalPublicKey over some message bytes. The message
        construction rule belongs to the identity business layer (out of scope for
        this test); this test can only have TS generate the message first and pass
        it to Python; here the actual verify is skipped (since we do not have the
        TS-side message), only asserting the fixture field types/formats are correct
        (guard against silent skip).
        """
        fixture_path = (
            _REPO_ROOT / "tests" / "fixtures" / "conformance" / "identity"
            / "binding-proof.json"
        )
        with fixture_path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        valid = data["valid"]
        assert len(valid) > 0

        for sample in valid:
            principal_pk_hex = sample["principalPublicKey"]
            signature_hex = sample["data"]["signature"]
            # As long as the fixture field formats are valid + Python decoding does not raise (guard against silent skip)
            assert len(principal_pk_hex) == 64
            assert len(signature_hex) == 128
            # The _decode_key_or_signature path does not raise (hex decode is valid)
            pk_bytes = from_hex(principal_pk_hex)
            sig_bytes = from_hex(signature_hex)
            assert len(pk_bytes) == 32
            assert len(sig_bytes) == 64
