#!/usr/bin/env python3
"""generate-hcc-reverse-fixtures.py — cross-lang HCC reverse fixture pipeline (Python Producer)

Role
----
Python HCC v0.2 (packages/sdk-python/src/coivitas/hash_chain_canonicalize)
acts as the Python Producer of cross-lang golden bytes; this script writes
`tests/fixtures/cross-lang/hcc-reverse-vectors.json`, which the TS side
(packages/crypto/test/hash-chain-canonicalize/cross-lang-reverse-fixture.test.ts)
consumes to verify byte-level parity (jcs / SHA-256 / preimage concat order / recursive hash linkage).

Usage
-----
  python3 scripts/generate-hcc-reverse-fixtures.py --regenerate
    → --regenerate mode: write hcc-reverse-vectors.json
  python3 scripts/generate-hcc-reverse-fixtures.py --check
    → --check mode: compare existing fixture against a fresh regeneration; diff → exit 1

Constraints
-----------
- fail-closed: in --check mode, a non-empty diff causes exit 1 plus a stderr diff dump
- deterministic: same input yields same output (does not rely on uuid.uuid4 / datetime.now)
  - entryId  = SHA-256(seed||position) → 16 byte → UUID v4 (version + variant set)
  - timestamp = "2026-05-25T00:00:00+00:00" + position-second offset (offset by 1 day from TS V1-V7)
- type boundaries: bytes / hex / string conversion points are annotated as boundaries
- anti-self-equal: hcc-reverse-vectors.json is generated by Python; the TS side reads the expected values from JSON rather than recomputing them

Vector set (RV1-RV7; different input from TS V1-V7 but the same structural coverage)
-----------------------------------------------------------
- RV1: single-entry chain (genesis only); chainIdentity = 1 field (chainNamespace only)
- RV2: 3-entry chain; same chainIdentity (policy/py-tenant-100/L2); simple payload schema
- RV3: 5-entry chain; same chainIdentity (governance/py-tenant-200/L3); multiple payload shapes (including nested + array)
- RV4: 3-entry chain; canonicalPayload contains Japanese Hiragana + Katakana + different emoji
       (similar to TS V4's use of CJK + emoji but with fully independent content; verifies JCS UTF-8 + field code-point ordering)
- RV5: 4-entry chain; chainIdentity multi-field combination (audit-py/py-tenant-500/L1); payload with numbers + null + bool
- RV6 NEGATIVE: mixed chainIdentity (3-entry; entry[1] uses py-audit-B); TS verifyHashChain must reject
- RV7 NEGATIVE: tampered canonicalPayloadHash (3-entry; last entry's hash hex final char is flipped); TS verify must reject

Authoritative sources
---------------------
- packages/sdk-python/src/coivitas/hash_chain_canonicalize/types.py (ChainIdentity + HashChainEntry)
- packages/sdk-python/src/coivitas/hash_chain_canonicalize/crypto.py (canonicalize_chain_identity +
  concat_preimage + compute_canonical_payload_hash_hex)

TS-side error-code naming (cross-lang convention)
---------------------------------------
Python raises with the HCC_* prefix (HccErrorCode StrEnum);
TS raises with the HC_* prefix (HashChainError 'HC_*' literal union).
This fixture's expected_reject_error_code field = the TS error code (HC_*); the TS test asserts against it directly when consuming.
- mixed-identity → HC_CHAIN_IDENTITY_PREIMAGE_FAILED (TS verify-hash-chain.ts)
- tampered hash  → HC_CHAIN_IDENTITY_PREIMAGE_FAILED (TS verify-helpers.ts;
  note: a hash mismatch inside TS assertCanonicalPayloadHashConsistent currently raises HC_CHAIN_IDENTITY_PREIMAGE_FAILED)
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

# ─── Path constants (scripts/ → sdk-python/ → packages/ → REPO_ROOT) ──────────────

_SCRIPT_DIR = Path(__file__).resolve().parent
_REPO_ROOT = _SCRIPT_DIR.parents[2]  # scripts → sdk-python → packages → REPO
_FIXTURE_OUT_DIR = _REPO_ROOT / "tests" / "fixtures" / "cross-lang"
_OUT_HCC_REVERSE = _FIXTURE_OUT_DIR / "hcc-reverse-vectors.json"

# Python SDK source import (ensure src is on sys.path)
_SDK_SRC = _SCRIPT_DIR.parent / "src"
sys.path.insert(0, str(_SDK_SRC))

from coivitas.hash_chain_canonicalize import (  # noqa: E402
    HCC_SENTINEL_HASH,
    HCC_VERSION,
    ChainIdentity,
    HashChainEntry,
    canonicalize_chain_identity,
    compute_canonical_payload_hash_hex,
    concat_preimage,
)
from coivitas.hash_chain_canonicalize.crypto import (  # noqa: E402
    _jcs_canonicalize,
)

# ─── Deterministic UUID v4 derivation (avoids the non-determinism of uuid.uuid4) ────────────────────


def _deterministic_uuid_v4(seed: str) -> str:
    """Derive a deterministic UUID v4 from a seed (same algorithm source as TS deterministicEntryId).

    Algorithm:
      1. SHA-256(seed) → 32 byte digest
      2. take the first 16 bytes
      3. byte[6] = (byte[6] & 0x0f) | 0x40   (version 4)
      4. byte[8] = (byte[8] & 0x3f) | 0x80   (variant 10)
      5. format as 8-4-4-4-12 hex

    Output looks like "a1b2c3d4-e5f6-4789-8abc-def012345678"; satisfies the RFC 4122 §4.4 UUID v4 format
    plus the AJV schema "format: uuid" plus the HashChainEntry schema "entryId.pattern".
    """
    # Type boundary: string → UTF-8 bytes → SHA-256 → 16 byte UUID
    digest = hashlib.sha256(seed.encode("utf-8")).digest()
    uuid_bytes = bytearray(digest[:16])
    uuid_bytes[6] = (uuid_bytes[6] & 0x0f) | 0x40
    uuid_bytes[8] = (uuid_bytes[8] & 0x3f) | 0x80
    # Type boundary: bytes → hex → UUID 8-4-4-4-12 format
    hex_str = uuid_bytes.hex()
    return (
        f"{hex_str[0:8]}-{hex_str[8:12]}-{hex_str[12:16]}-"
        f"{hex_str[16:20]}-{hex_str[20:32]}"
    )


def _deterministic_entry_id(seed: str, position: int) -> str:
    """Derive a deterministic entry UUID v4 from (seed, position).

    The seed/position pair is unique (same vector_id + position) → same output UUID.
    """
    return _deterministic_uuid_v4(f"{seed}:{position}")


def _deterministic_tenant_id(seed: str) -> str:
    """Derive a deterministic tenant UUID v4 from a seed.

    The AJV schema (hash-chain-entry-v0.2.schema.json $defs.ChainIdentity.tenantId)
    requires tenantId format=uuid; the Python Producer must use the UUID v4 format
    (TS verifyHashChain runs AJV strict and will reject any non-UUID tenantId).
    seed = vector_id + "/tenant" is unique → same vector yields the same UUID; different vectors yield different UUIDs.
    """
    return _deterministic_uuid_v4(f"{seed}/tenant")


def _deterministic_timestamp(position: int) -> str:
    """Derive an ISO 8601 UTC timestamp from a position; output uses a Z suffix plus millisecond precision.

    Format "2026-05-25T00:00:00.000Z" + position-second offset (offset by 1 day from the TS Producer's 2026-05-24;
    ensures the cross-lang fixture cannot false-pass against each other due to a coincidental timestamp).

    Critical: the output format must be compatible with the TS HashChainEntry schema (AJV date-time format).
    The TS Producer uses `new Date(...).toISOString()`, producing "YYYY-MM-DDTHH:MM:SS.sssZ" (Z suffix + 3-digit milliseconds);
    Python's default `.isoformat()` produces a "+00:00" suffix with no milliseconds, which the AJV schema would reject.
    This function formats manually into the TS-equivalent format.
    """
    base = datetime(2026, 5, 25, 0, 0, 0, tzinfo=timezone.utc)
    ts = base + timedelta(seconds=position)
    # Format manually as "YYYY-MM-DDTHH:MM:SS.sssZ" (aligned with TS Date.toISOString() output)
    # strftime does not directly support milliseconds; manually append ".000Z"
    return ts.strftime("%Y-%m-%dT%H:%M:%S.000Z")


# ─── HashChainEntry construction (fully deterministic; does not use append_hash_chain_entry, which calls uuid.uuid4 + datetime.now) ─


def _build_deterministic_entry(
    payload: dict[str, Any],
    chain_identity: ChainIdentity,
    prev_entry: HashChainEntry | None,
    vector_seed: str,
) -> HashChainEntry:
    """Construct a HashChainEntry from (payload, chainIdentity, prevEntry, vectorSeed).

    Uses the same algorithm as append_hash_chain_entry (preimage = canonicalPayloadBytes || chainIdentityJcsBytes); differences:
      - entryId: deterministically derived (vs uuid.uuid4)
      - timestamp: deterministically derived (vs datetime.now)
      - no prev_entry chainIdentity continuity guard (the caller's RV6 negative vector needs to build a mixed chain)
    """
    # Step 1: payload JCS canonicalize → canonicalPayload string
    canonical_payload_bytes: bytes = _jcs_canonicalize(payload)
    canonical_payload: str = canonical_payload_bytes.decode("utf-8")

    # Step 2: chainIdentity JCS canonicalize → ChainIdentityJcs brand
    chain_identity_jcs = canonicalize_chain_identity(chain_identity)

    # Step 3: preimage = UTF8(canonicalPayload) || chainIdentityJcsBytes
    preimage = concat_preimage(canonical_payload, chain_identity_jcs)

    # Step 4: SHA-256 → canonicalPayloadHash hex (64 lowercase)
    canonical_payload_hash: str = compute_canonical_payload_hash_hex(preimage)

    # Step 5: previousHash (genesis = 64 zeros OR prev.canonicalPayloadHash)
    previous_hash: str = (
        HCC_SENTINEL_HASH if prev_entry is None else prev_entry.canonicalPayloadHash
    )

    # Step 6: chainPosition
    position_num: int = 0 if prev_entry is None else prev_entry.chainPosition + 1

    # Step 7: deterministic entryId + timestamp
    entry_id = _deterministic_entry_id(vector_seed, position_num)
    timestamp = _deterministic_timestamp(position_num)

    return HashChainEntry(
        entryId=entry_id,
        canonicalPayload=canonical_payload,
        canonicalPayloadHash=canonical_payload_hash,
        previousHash=previous_hash,
        chainPosition=position_num,
        chainIdentity=dict(chain_identity),
        timestamp=timestamp,
        hccVersion=HCC_VERSION,
    )


# ─── Vector spec (symmetric with TS VectorSpec; Python dataclass) ─────────────────


@dataclass
class VectorSpec:
    id: str
    description: str
    chain_identity: ChainIdentity
    payloads: list[dict[str, Any]]
    expected_verify_outcome: str  # "PASS" | "REJECT"
    expected_reject_error_substring: str | None = None
    expected_reject_error_code: str | None = None  # TS HC_* prefix
    tamper_description: str | None = None
    mixed_identity_at: int | None = None  # the Nth entry uses a replacement chainIdentity
    mixed_identity_value: ChainIdentity | None = None
    # tamper the last entry's hash at the Nth character (flip the final char counting from the right)
    tamper_last_hash_char_index: int | None = None


# RV1-RV7 specs (fully independent of TS V1-V7 input; reuse no chainNamespace/tenantId/payload)
# tenantId constraint: the AJV schema (hash-chain-entry-v0.2.schema.json $defs.ChainIdentity.tenantId)
# requires format=uuid; the Python Producer must use a deterministic UUID v4 (derived via _deterministic_tenant_id)
# filled in during vector assembly; here the spec uses placeholder "__TENANT_<key>__" strings for easy replacement during assembly.

_VECTOR_SPECS: list[VectorSpec] = [
    VectorSpec(
        id="RV1-py-genesis-only",
        description=(
            "RV1: single-entry chain (genesis only); chainIdentity has 1 field only "
            "(chainNamespace only, no tenantId/auditClass); minimal ASCII payload; "
            "distinct from TS V1's three-field identity"
        ),
        chain_identity={"chainNamespace": "py-genesis"},
        payloads=[
            {
                "event": "py-init",
                "creator": "did:agent:py-rv1-creator",
                "seq": 0,
            },
        ],
        expected_verify_outcome="PASS",
    ),
    VectorSpec(
        id="RV2-py-three-entry-chain",
        description=(
            "RV2: 3-entry chain; same chainIdentity (policy + UUID tenantId + L2); "
            "simple payload schema (action + sequence + actor); recursive hash linkage"
        ),
        chain_identity={
            "chainNamespace": "policy",
            "tenantId": "__TENANT_RV2__",
            "auditClass": "L2",
        },
        payloads=[
            {"action": "start", "sequence": 0, "actor": "did:agent:py-rv2-actor"},
            {
                "action": "process",
                "sequence": 1,
                "actor": "did:agent:py-rv2-actor",
                "ref": "start-completed",
            },
            {
                "action": "commit",
                "sequence": 2,
                "actor": "did:agent:py-rv2-actor",
                "outcome": "success",
            },
        ],
        expected_verify_outcome="PASS",
    ),
    VectorSpec(
        id="RV3-py-five-entry-chain",
        description=(
            "RV3: 5-entry chain; same chainIdentity (governance + UUID tenantId + L3); "
            "multiple payload shapes (including nested + array; differing schema across entries)"
        ),
        chain_identity={
            "chainNamespace": "governance",
            "tenantId": "__TENANT_RV3__",
            "auditClass": "L3",
        },
        payloads=[
            {"kind": "motion", "id": "mot-py-001", "supporters": []},
            {
                "kind": "endorse",
                "motionId": "mot-py-001",
                "endorser": "did:agent:py-rv3-e1",
                "weight": 3,
            },
            {
                "kind": "endorse",
                "motionId": "mot-py-001",
                "endorser": "did:agent:py-rv3-e2",
                "weight": 1,
            },
            {
                "kind": "threshold-passed",
                "motionId": "mot-py-001",
                "nested": {"required": 3, "achieved": 4},
            },
            {
                "kind": "enact",
                "motionId": "mot-py-001",
                "actions": ["enact-1", "enact-2", "enact-3"],
                "effective_at": "2026-05-25",
            },
        ],
        expected_verify_outcome="PASS",
    ),
    VectorSpec(
        id="RV4-py-japanese-emoji-payload",
        description=(
            "RV4: 3-entry chain; canonicalPayload contains Japanese Hiragana + Katakana + "
            "distinct emoji (🦀 / 🐍 / 🌸); content fully independent of TS V4's CJK "
            "(avoids cross-validation false positives); verifies Python JCS UTF-8 + field "
            "code-point ordering matches TS at the byte level"
        ),
        chain_identity={
            "chainNamespace": "audit-jp",
            "tenantId": "__TENANT_RV4__",
            "auditClass": "L2",
        },
        payloads=[
            {
                "イベント": "開始",
                "actor": "did:agent:日本語",
                "marker": "🦀",
            },
            {
                "イベント": "進行",
                "actor": "did:agent:日本語",
                "ラベル": ["タグ1", "タグ2", "🐍"],
            },
            {
                "イベント": "完了",
                "actor": "did:agent:日本語",
                "要約": "ASCII + ひらがな + カタカナ + emoji 🌸",
            },
        ],
        expected_verify_outcome="PASS",
    ),
    VectorSpec(
        id="RV5-py-multi-field-identity",
        description=(
            "RV5: 4-entry chain; chainIdentity uses all three fields (audit-py + UUID tenantId + L1); "
            "payload mixes numbers + null + bool in various combinations (verifies JCS primitive ordering)"
        ),
        chain_identity={
            "chainNamespace": "audit-py",
            "tenantId": "__TENANT_RV5__",
            "auditClass": "L1",
        },
        payloads=[
            {"phase": "draft", "score": 0, "approved": False},
            {
                "phase": "review",
                "score": 50,
                "approved": False,
                "reviewer": None,
            },
            {
                "phase": "approve",
                "score": 85,
                "approved": True,
                "reviewer": "did:agent:py-rv5-reviewer",
            },
            {
                "phase": "publish",
                "score": 100,
                "approved": True,
                "reviewer": "did:agent:py-rv5-publisher",
            },
        ],
        expected_verify_outcome="PASS",
    ),
    VectorSpec(
        id="RV6-py-NEGATIVE-mixed-identity",
        description=(
            "RV6 NEGATIVE: 3-entry chain; entry[1]'s chainIdentity differs from entry[0]/entry[2] "
            "(identity-rebinding); TS verifyHashChain must reject via the chain-level identity "
            "consistency check (HC_CHAIN_IDENTITY_PREIMAGE_FAILED)"
        ),
        chain_identity={
            "chainNamespace": "py-audit-A",
            "tenantId": "__TENANT_RV6_A__",
            "auditClass": "L1",
        },
        payloads=[
            {"ev": "py-a-0"},
            {"ev": "py-a-1"},
            {"ev": "py-a-2"},
        ],
        expected_verify_outcome="REJECT",
        expected_reject_error_substring="mixed-identity",
        expected_reject_error_code="HC_CHAIN_IDENTITY_PREIMAGE_FAILED",
        tamper_description=(
            "entry[1].chainIdentity replaced with a different tenant (py-audit-B + a different "
            "UUID tenantId); previousHash linkage preserved (fabricated to look legitimate); "
            "TS verify must reject via the chain-level identity consistency check "
            "(verify-hash-chain.ts L315-320 is the real anchor)"
        ),
        mixed_identity_at=1,
        mixed_identity_value={
            "chainNamespace": "py-audit-B",
            "tenantId": "__TENANT_RV6_B__",
            "auditClass": "L1",
        },
    ),
    VectorSpec(
        id="RV7-py-NEGATIVE-tampered-hash",
        description=(
            "RV7 NEGATIVE: 3-entry chain; the last entry's canonicalPayloadHash final char is "
            "flipped (0 <-> f, 1 <-> e, ...); TS verifyHashChain must reject via "
            "assertCanonicalPayloadHashConsistent (HC_CHAIN_IDENTITY_PREIMAGE_FAILED; "
            "verify-helpers.ts L189-191 is the real anchor)"
        ),
        chain_identity={
            "chainNamespace": "py-audit-tamper",
            "tenantId": "__TENANT_RV7__",
            "auditClass": "L2",
        },
        payloads=[
            {"ev": "py-t-0"},
            {"ev": "py-t-1"},
            {"ev": "py-t-2"},
        ],
        expected_verify_outcome="REJECT",
        expected_reject_error_substring="recomputed",
        expected_reject_error_code="HC_CHAIN_IDENTITY_PREIMAGE_FAILED",
        tamper_description=(
            "entry[2].canonicalPayloadHash final char flipped (0->f / a->5 etc.); after TS "
            "recompute, the result != stored canonicalPayloadHash -> HC_CHAIN_IDENTITY_PREIMAGE_FAILED reject"
        ),
        tamper_last_hash_char_index=-1,  # last char
    ),
]


def _resolve_tenant_placeholders() -> None:
    """Replace every "__TENANT_<key>__" placeholder in _VECTOR_SPECS with a deterministic UUID v4.

    Each placeholder key is unique (RV2 / RV3 / ... / RV6_A / RV6_B / RV7) → derives a distinct tenant UUID.
    Runs once at module load; must be called before assembling entries (idempotent).
    """
    placeholder_prefix = "__TENANT_"
    placeholder_suffix = "__"
    for spec in _VECTOR_SPECS:
        for identity_dict in [spec.chain_identity, spec.mixed_identity_value]:
            if identity_dict is None:
                continue
            tenant_val = identity_dict.get("tenantId")
            if (
                tenant_val is not None
                and tenant_val.startswith(placeholder_prefix)
                and tenant_val.endswith(placeholder_suffix)
            ):
                key = tenant_val[len(placeholder_prefix):-len(placeholder_suffix)]
                identity_dict["tenantId"] = _deterministic_tenant_id(key)


# Resolve placeholders immediately at module load (ensures _build_vector_output gets the UUIDs when called)
_resolve_tenant_placeholders()


# ─── Vector → entries[] + expected[] assembly ─────────────────────────────────


_HEX_FLIP_MAP: dict[str, str] = {
    "0": "f", "1": "e", "2": "d", "3": "c",
    "4": "b", "5": "a", "6": "9", "7": "8",
    "8": "7", "9": "6", "a": "5", "b": "4",
    "c": "3", "d": "2", "e": "1", "f": "0",
}


def _flip_hex_char(c: str) -> str:
    """One-to-one flip of a hex char (0↔f / 1↔e / ... / 7↔8)."""
    out = _HEX_FLIP_MAP.get(c)
    if out is None:
        raise ValueError(f"_flip_hex_char: unexpected char {c!r}")
    return out


@dataclass
class VectorFixtureOutput:
    id: str
    description: str
    chainIdentity: dict[str, str]
    entries: list[dict[str, Any]]  # HashChainEntry.model_dump()
    expected_concat_preimage_hex_per_position: list[str]
    expected_canonical_payload_hash_per_position: list[str]
    expected_final_hash: str
    expected_verify_outcome: str
    expected_reject_error_substring: str | None = None
    expected_reject_error_code: str | None = None
    tamper_description: str | None = None


def _build_vector_output(spec: VectorSpec) -> VectorFixtureOutput:
    entries: list[HashChainEntry] = []
    expected_preimages: list[str] = []
    expected_hashes: list[str] = []
    prev: HashChainEntry | None = None

    for i, payload in enumerate(spec.payloads):
        # Decide which chainIdentity this entry uses (RV6 mixed-identity switches at the specified position)
        if spec.mixed_identity_at == i and spec.mixed_identity_value is not None:
            used_identity = spec.mixed_identity_value
        else:
            used_identity = spec.chain_identity

        entry = _build_deterministic_entry(
            payload=payload,
            chain_identity=used_identity,
            prev_entry=prev,
            vector_seed=spec.id,
        )

        # Compute preimage hex (cross-lang anchor for the TS consumer)
        identity_jcs = canonicalize_chain_identity(used_identity)
        preimage = concat_preimage(entry.canonicalPayload, identity_jcs)
        # Type boundary: bytes → hex
        preimage_hex = preimage.hex()

        expected_preimages.append(preimage_hex)
        expected_hashes.append(entry.canonicalPayloadHash)
        entries.append(entry)
        prev = entry

    # RV7 tampered hash: replace the specified char of the last entry's canonicalPayloadHash
    # Note: expected_canonical_payload_hash_per_position retains the original correct value
    #    (the TS consumer recomputing from the preimage should arrive at the original value);
    #    entries[-1].canonicalPayloadHash is tampered to the flipped value (TS verify should reject).
    if (
        spec.expected_verify_outcome == "REJECT"
        and spec.tamper_last_hash_char_index is not None
        and len(entries) > 0
    ):
        idx = spec.tamper_last_hash_char_index
        last_entry = entries[-1]
        orig = last_entry.canonicalPayloadHash
        # Support negative indexing (-1 = last char); Python string slicing handles it naturally
        if idx < 0:
            real_idx = len(orig) + idx
        else:
            real_idx = idx
        flipped = orig[:real_idx] + _flip_hex_char(orig[real_idx]) + orig[real_idx + 1:]
        # Verify it is still 64 lowercase hex chars (satisfies the HashChainEntry validator)
        assert len(flipped) == 64
        # Reconstruct the entry (pydantic strict → use model_copy)
        tampered_entry = last_entry.model_copy(update={"canonicalPayloadHash": flipped})
        entries[-1] = tampered_entry
        # expected_canonical_payload_hash_per_position retains the original (pre-tamper) value; not changed

    # entries → dict (model_dump); ensure field order matches TS HashChainEntry (aligned with the TS Producer)
    entry_dicts: list[dict[str, Any]] = []
    for entry in entries:
        # model_dump (mode='python') yields an OrderedDict; pydantic v2 preserves field definition order
        # but to keep JSON serialization cross-lang reproducible, output explicitly in TS HashChainEntry field-definition order
        # TS interface order: entryId, canonicalPayload, canonicalPayloadHash, previousHash,
        #                    chainPosition, chainIdentity, timestamp, hccVersion
        entry_dicts.append({
            "entryId": entry.entryId,
            "canonicalPayload": entry.canonicalPayload,
            "canonicalPayloadHash": entry.canonicalPayloadHash,
            "previousHash": entry.previousHash,
            "chainPosition": entry.chainPosition,
            "chainIdentity": entry.chainIdentity,
            "timestamp": entry.timestamp,
            "hccVersion": entry.hccVersion,
        })

    return VectorFixtureOutput(
        id=spec.id,
        description=spec.description,
        chainIdentity=dict(spec.chain_identity),
        entries=entry_dicts,
        expected_concat_preimage_hex_per_position=expected_preimages,
        expected_canonical_payload_hash_per_position=expected_hashes,
        expected_final_hash=expected_hashes[-1],
        expected_verify_outcome=spec.expected_verify_outcome,
        expected_reject_error_substring=spec.expected_reject_error_substring,
        expected_reject_error_code=spec.expected_reject_error_code,
        tamper_description=spec.tamper_description,
    )


def _generate_hcc_reverse_vectors() -> dict[str, Any]:
    """Generate the complete fixture dict (structurally symmetric with the TS Producer output)."""
    vectors = [_build_vector_output(spec) for spec in _VECTOR_SPECS]
    # Field names use snake_case (Python convention);
    # the top-level structure parallels TS hcc-vectors.json (version + generated_by + lib metadata)
    return {
        "version": "v0.2",
        "generated_by": (
            "packages/sdk-python/scripts/generate-hcc-reverse-fixtures.py"
        ),
        "python_canonicalize_lib": "jcs (or stdlib JCS fallback)",
        "python_hash_lib": "hashlib.sha256 (Python stdlib;HCC v0.2)",
        "hcc_version": HCC_VERSION,
        "preimage_order": (
            "canonicalPayloadBytes || chainIdentityJcsBytes "
            "(cross-lang, consistent with the TS Producer)"
        ),
        "vectors": [_vector_output_to_dict(v) for v in vectors],
    }


def _vector_output_to_dict(v: VectorFixtureOutput) -> dict[str, Any]:
    """VectorFixtureOutput dataclass → dict (ensure None fields are omitted); aligned with the TS output."""
    base: dict[str, Any] = {
        "id": v.id,
        "description": v.description,
        "chainIdentity": v.chainIdentity,
        "entries": v.entries,
        "expected_concat_preimage_hex_per_position": v.expected_concat_preimage_hex_per_position,
        "expected_canonical_payload_hash_per_position": v.expected_canonical_payload_hash_per_position,
        "expected_final_hash": v.expected_final_hash,
        "expected_verify_outcome": v.expected_verify_outcome,
    }
    if v.expected_reject_error_substring is not None:
        base["expected_reject_error_substring"] = v.expected_reject_error_substring
    if v.expected_reject_error_code is not None:
        base["expected_reject_error_code"] = v.expected_reject_error_code
    if v.tamper_description is not None:
        base["tamper_description"] = v.tamper_description
    return base


# ─── Serialize + write / check (same pattern as the TS Producer; 4-space indent + ensure_ascii=False) ─


def _serialize_fixture(data: dict[str, Any]) -> str:
    """JSON serialization (4-space indent; ensure_ascii=False to keep Unicode readable; trailing newline).

    Aligned with the TS Producer's JSON.stringify(data, null, 4) output structure (top-level + nested indentation);
    Unicode characters (RV4 Japanese + emoji) retain raw UTF-8 encoding (rather than \\uXXXX escapes).
    """
    return json.dumps(data, indent=4, ensure_ascii=False, sort_keys=False)


def _run_regenerate() -> None:
    _FIXTURE_OUT_DIR.mkdir(parents=True, exist_ok=True)
    data = _generate_hcc_reverse_vectors()
    serialized = _serialize_fixture(data) + "\n"
    _OUT_HCC_REVERSE.write_text(serialized, encoding="utf-8")
    sys.stdout.write(
        f"[hcc-reverse-fixtures:regenerate] wrote 1 fixture file:\n"
        f"  {_OUT_HCC_REVERSE}\n"
        f"  vectors: {len(_VECTOR_SPECS)}\n"
        f"  hcc_version: {HCC_VERSION}\n"
    )


def _run_check() -> None:
    expected_content = _serialize_fixture(_generate_hcc_reverse_vectors()) + "\n"

    if not _OUT_HCC_REVERSE.exists():
        sys.stderr.write(
            f"[hcc-reverse-fixtures:check] FAIL — fixture file missing:\n"
            f"  {_OUT_HCC_REVERSE}\n"
            f"Run 'python3 scripts/generate-hcc-reverse-fixtures.py --regenerate' "
            f"and commit the result.\n"
        )
        sys.exit(1)

    actual = _OUT_HCC_REVERSE.read_text(encoding="utf-8")
    if actual == expected_content:
        sys.stdout.write(
            "[hcc-reverse-fixtures:check] PASS — hcc-reverse-vectors.json "
            "matches Python output.\n"
        )
        return

    # Line-level diff summary (fail-closed: dump diff to stderr; at most 20 lines)
    actual_lines = actual.split("\n")
    expected_lines = expected_content.split("\n")
    max_len = max(len(actual_lines), len(expected_lines))
    diff_lines: list[str] = [f"DIFF in {_OUT_HCC_REVERSE}:"]
    diff_count = 0
    for i in range(max_len):
        if diff_count >= 20:
            break
        a = actual_lines[i] if i < len(actual_lines) else "(missing)"
        e = expected_lines[i] if i < len(expected_lines) else "(missing)"
        if a != e:
            diff_lines.append(f"  line {i + 1}: actual  = {a}")
            diff_lines.append(f"  line {i + 1}: expected= {e}")
            diff_count += 1
    if diff_count >= 20:
        diff_lines.append("  ... (truncated at 20 diff lines)")
    sys.stderr.write(
        f"[hcc-reverse-fixtures:check] FAIL — hcc-reverse-vectors.json is stale.\n"
        f"Run 'python3 scripts/generate-hcc-reverse-fixtures.py --regenerate' "
        f"and commit the updated fixture file.\n\n"
        + "\n".join(diff_lines)
        + "\n"
    )
    sys.exit(1)


# ─── Entry point ────────────────────────────────────────────────────


def _main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate / check cross-lang HCC reverse fixture "
            "(Python Producer → TS Consumer)"
        )
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--regenerate",
        action="store_true",
        help="Write hcc-reverse-vectors.json (deterministic)",
    )
    group.add_argument(
        "--check",
        action="store_true",
        help="Compare existing fixture vs. fresh generation;exit 1 if diff",
    )
    args = parser.parse_args()

    if args.regenerate:
        _run_regenerate()
    elif args.check:
        _run_check()


if __name__ == "__main__":
    _main()
